import json

problems_data = [
    {
        'id': 'mux_2to1',
        'title': '2:1 Multiplexer',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['mux', 'selector', 'combinational'],
        'module_signature': 'module mux_2to1(input [7:0] a, input [7:0] b, input sel, output [7:0] y);',
        'statement': 'Implement a 2:1 multiplexer that selects between two 8-bit inputs based on a single select line. The module must drive the output combinationally with no registers or clocks. The select signal must be stable during evaluation. This circuit is a classic data-path selector used in ALU and routing logic.',
        'behavior': ['If sel is 0, y must equal a; if sel is 1, y must equal b.', 'No sequential elements; behavior must be purely combinational.', 'All bits of y must update immediately after inputs change.'],
        'constraints': 'Do not use any clocks or sequential constructs.',
        'example': 'a b sel | y\n00000000 11111111 0 | 00000000\n00000000 11111111 1 | 11111111\n10101010 01010101 1 | 01010101',
        'hint': 'Use a single conditional assignment or bitwise mask.'
    },
    {
        'id': 'decoder_3to8',
        'title': '3-to-8 Decoder',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['decoder', 'one-hot', 'combinational'],
        'module_signature': 'module decoder_3to8(input [2:0] sel, output [7:0] y);',
        'statement': 'Design a 3-to-8 decoder that converts a 3-bit binary input into an eight-bit one-hot output. Only one output line may be asserted at a time while all others remain low. If the input is out of range, all outputs should remain zero. This module is often used in address decoding and instruction dispatch logic.',
        'behavior': ['One-hot output: y[i] = 1 when sel equals i, else 0.', 'All outputs must be driven combinationally.', 'No use of memories, latches, or sequential blocks.'],
        'constraints': 'Do not use a behavioral for-loop for the decoder.',
        'example': 'sel | y\n000 | 00000001\n010 | 00000100\n111 | 10000000',
        'hint': 'Think of the decoder as a binary-to-one-hot converter.'
    },
    {
        'id': 'priority_encoder_8to3',
        'title': '8-to-3 Priority Encoder',
        'difficulty': 'Medium',
        'category': 'Combinational',
        'tags': ['priority', 'encoder', 'combinational'],
        'module_signature': 'module priority_encoder_8to3(input [7:0] in, output reg [2:0] code, output valid);',
        'statement': 'Create an 8-to-3 priority encoder that encodes the highest-priority asserted input into a binary output. Input 7 has the highest priority and input 0 the lowest. If no inputs are asserted, output should be zero and valid must be low. The encoder must resolve priority with a single combinational pass.',
        'behavior': ['code indicates the index of the highest asserted input.', 'valid is 1 when any input bit is high, else 0.', 'Behavior must be purely combinational despite reg output syntax.'],
        'constraints': 'Do not use sequential procedural loops or clocked always blocks.',
        'example': 'in       | valid code\n00000000 | 0 000\n00010010 | 1 100\n10000001 | 1 111',
        'hint': 'Evaluate inputs from highest to lowest priority.'
    },
    {
        'id': 'comparator_unsigned',
        'title': 'Unsigned Comparator',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['comparator', 'comparison', 'combinational'],
        'module_signature': 'module comparator_unsigned(input [7:0] a, input [7:0] b, output gt, output eq, output lt);',
        'statement': 'Build an unsigned comparator that compares two 8-bit operands and reports greater-than, equal, and less-than conditions. The outputs must reflect the result of the comparison for every change of the inputs. This module is pure combinational logic and must not infer any storage elements.',
        'behavior': ['gt is 1 when a > b.', 'eq is 1 when a == b.', 'lt is 1 when a < b.'],
        'constraints': 'Do not use sequential constructs or case statements with hidden registers.',
        'example': 'a b | gt eq lt\n00000001 00000010 | 0 0 1\n00000011 00000011 | 0 1 0\n11111111 00000000 | 1 0 0',
        'hint': 'You can derive lt from gt and eq if you like.'
    },
    {
        'id': 'even_parity_generator',
        'title': 'Even Parity Generator',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['parity', 'reduction', 'combinational'],
        'module_signature': 'module even_parity_generator(input [7:0] a, output parity);',
        'statement': 'Implement an even parity generator for an 8-bit input. The output should be high when the input contains an even number of ones. The module must be stable for all input vectors and suitable for parity checking in simple link-layer circuits.',
        'behavior': ['parity is 1 when the number of 1 bits in a is even.', 'parity is 0 when the number of 1 bits is odd.', 'No sequential or clocked logic may be used.'],
        'constraints': 'Do not use built-in reduction XOR directly if you want a structural solution.',
        'example': 'a        | parity\n00000000 | 1\n00000001 | 0\n10101010 | 1',
        'hint': 'Treat parity as a multi-input XOR reduction with inverted output.'
    },
    {
        'id': 'sign_extender_8to16',
        'title': 'Sign Extender',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['sign-extender', 'datapath', 'combinational'],
        'module_signature': 'module sign_extender(input [7:0] a, output [15:0] y);',
        'statement': 'Design an 8-bit sign extender that converts a signed 8-bit input into a 16-bit two’s complement output. The top 8 bits of the result must be copies of the input sign bit. The module is used in datapath code to widen signed values before arithmetic.',
        'behavior': ['y[7:0] must equal a.', 'y[15:8] must be all 1s when a[7] is 1 and all 0s when a[7] is 0.', 'Only combinational logic is allowed.'],
        'constraints': 'Do not use sequential constructs or memory elements.',
        'example': 'a        | y\n10000000 | 11111111_10000000\n01111111 | 00000000_01111111',
        'hint': 'Copy the sign bit across the upper bits.'
    },
    {
        'id': 'zero_detector',
        'title': 'Zero Detector',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['comparator', 'detector', 'combinational'],
        'module_signature': 'module zero_detector(input [7:0] a, output is_zero);',
        'statement': 'Create an 8-bit zero detector that asserts output when all bits of the input are zero. The circuit should return zero otherwise. It is a simple combinational check used in branch condition generation and comparator datapaths.',
        'behavior': ['is_zero is 1 when a == 0.', 'is_zero is 0 for any nonzero input.', 'Do not infer registers or sequential logic.'],
        'constraints': 'Do not use a sequential loop or latch inference.',
        'example': 'a        | is_zero\n00000000 | 1\n00000001 | 0\n11111111 | 0',
        'hint': 'All bits must be compared to zero in a single combinational expression.'
    },
    {
        'id': 'one_hot_to_binary',
        'title': 'One-Hot to Binary Encoder',
        'difficulty': 'Medium',
        'category': 'Combinational',
        'tags': ['encoder', 'one-hot', 'combinational'],
        'module_signature': 'module one_hot_to_binary(input [7:0] one_hot, output reg [2:0] code, output valid);',
        'statement': 'Design a one-hot to binary encoder that converts an eight-bit one-hot input into a 3-bit binary output plus a valid signal. If the input is not one-hot or is all zeros, valid must be 0 and code must be 0. This module is useful in priority schemes and state decoders.',
        'behavior': ['code reports the position of the asserted bit if exactly one input is high.', 'valid is 1 only if exactly one input bit is high.', 'If zero or multiple bits are asserted, valid is 0 and code is 0.'],
        'constraints': 'Do not use sequential pipelines or internal state.',
        'example': 'one_hot | valid code\n00000000 | 0 000\n00010000 | 1 100\n11000000 | 0 000',
        'hint': 'Count the asserted signals and encode only when the count is one.'
    },
    {
        'id': 'majority_gate',
        'title': '3-Input Majority Gate',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['majority', 'voting', 'combinational'],
        'module_signature': 'module majority_gate(input a, input b, input c, output y);',
        'statement': 'Build a 3-input majority gate that outputs 1 when at least two of the three inputs are 1. The output must be low for one or zero asserted inputs. It is a basic voting circuit used in fault-tolerant systems and combinational logic designs.',
        'behavior': ['y is 1 when two or three inputs are 1.', 'y is 0 when zero or one inputs are 1.', 'The design must be pure combinational logic.'],
        'constraints': 'Avoid sequential constructs and latches.',
        'example': 'a b c | y\n0 0 0 | 0\n1 1 0 | 1\n1 1 1 | 1',
        'hint': 'Compute the sum of the bits and compare to two.'
    },
    {
        'id': 'detect_msb_one',
        'title': 'MSB One Detector',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['detector', 'combinational', 'bit-scan'],
        'module_signature': 'module detect_msb_one(input [7:0] a, output msb_one);',
        'statement': 'Design an 8-bit detector that asserts output when the most significant bit of the input is 1. The circuit should ignore lower bits and react combinationally to input changes. This is useful for sign detection and branch decisions in unsigned comparisons.',
        'behavior': ['msb_one is 1 when a[7] is 1.', 'msb_one is 0 otherwise.', 'No sequential or clocked logic is permitted.'],
        'constraints': 'Do not use any registers or case-statements that infer state.',
        'example': 'a        | msb_one\n10000000 | 1\n01111111 | 0',
        'hint': 'Only the top bit determines the output.'
    },
    {
        'id': 'carry_generate_combiner',
        'title': 'Carry Generate Combiner',
        'difficulty': 'Medium',
        'category': 'Combinational',
        'tags': ['carry', 'adder', 'combinational'],
        'module_signature': 'module carry_generate_combiner(input [7:0] a, input [7:0] b, output g, output p);',
        'statement': 'Implement an 8-bit carry generate and propagate unit that produces group generate and group propagate signals for a ripple-carry adder stage. The outputs should describe whether this block will generate a carry regardless of input carry, or propagate an input carry to the next stage. This combinational module is a datapath building block used in faster adder designs.',
        'behavior': ['g is 1 when a+b will generate a carry within the block regardless of carry-in.', 'p is 1 when the block propagates a carry-in to carry-out.', 'The design must be purely combinational.'],
        'constraints': 'Do not instantiate a full adder array with registers.',
        'example': 'a b | g p\n00000000 00000001 | 0 0\n11111111 00000001 | 1 0\n01010101 10101010 | 0 1',
        'hint': 'Use bitwise and/or reduction logic to capture generate and propagate behavior.'
    },
    {
        'id': 'min_max_selector',
        'title': 'Min/Max Selector',
        'difficulty': 'Medium',
        'category': 'Combinational',
        'tags': ['selector', 'comparator', 'datapath'],
        'module_signature': 'module min_max_selector(input signed [7:0] a, input signed [7:0] b, input sel, output signed [7:0] y);',
        'statement': 'Create a combinational min/max selector that chooses either the smaller or larger of two 8-bit signed inputs based on a control input. When sel is 0, output the minimum; when sel is 1, output the maximum. The module should handle two’s complement operands correctly and produce valid signed results.',
        'behavior': ['When sel is 0, y equals the smaller signed operand.', 'When sel is 1, y equals the larger signed operand.', 'Equal operands may output either value.'],
        'constraints': 'Do not use sequential logic or registers.',
        'example': 'a b sel | y\n00000001 00000010 0 | 00000001\n11111111 00000001 1 | 00000001',
        'hint': 'Compare operands as signed numbers, not unsigned.'
    },
    {
        'id': 'threshold_detector',
        'title': 'Threshold Detector',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['threshold', 'comparator', 'combinational'],
        'module_signature': 'module threshold_detector(input [7:0] a, output above_threshold);',
        'statement': 'Build an 8-bit threshold detector that asserts output when the input exceeds a fixed constant value of 100 decimal. The output must be high for 101 and greater, and low for 100 and below. This is a common operation in analog-to-digital and control circuits.',
        'behavior': ['above_threshold is 1 when a > 100.', 'above_threshold is 0 when a <= 100.', 'The logic must be purely combinational.'],
        'constraints': 'Do not use a sequential comparator or state machine.',
        'example': 'a      | above_threshold\n01100100 | 0\n01100101 | 1\n10000000 | 1',
        'hint': 'Hardcode the threshold comparison with bitwise logic if needed.'
    },
    {
        'id': 'absolute_value_unit',
        'title': 'Absolute Value Unit',
        'difficulty': 'Medium',
        'category': 'Combinational',
        'tags': ['absolute', 'signed', 'datapath'],
        'module_signature': 'module absolute_value_unit(input signed [7:0] a, output reg [7:0] y);',
        'statement': 'Design an absolute value unit that converts a signed 8-bit input to its nonnegative magnitude. The output should be the input when nonnegative and the two’s complement negation when negative. This module is used in datapath units requiring magnitude comparisons.',
        'behavior': ['y is equal to a when a is nonnegative.', 'y is equal to -a when a is negative.', 'The design must be combinational.'],
        'constraints': 'Do not infer sequential storage or clocks.',
        'example': 'a | y\n00000011 | 00000011\n11111101 | 00000011',
        'hint': 'Select between a and its negation based on the sign bit.'
    },
    {
        'id': 'bitwise_nand',
        'title': 'Bitwise NAND',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['nand', 'bitwise', 'combinational'],
        'module_signature': 'module bitwise_nand(input [7:0] a, input [7:0] b, output [7:0] y);',
        'statement': 'Create an 8-bit bitwise NAND operator. The output should be the bitwise NAND of the two 8-bit inputs. This module is useful for building logic functions and implementing complex logic gates.',
        'behavior': ['y is the bitwise NAND of a and b.', 'The result is 1 for each bit pair that is not both 1.', 'The design must be combinational.'],
        'constraints': 'Do not use registers or sequential constructs.',
        'example': 'a b | y\n11110000 10101010 | 01010101',
        'hint': 'Use bitwise operators directly for the NAND operation.'
    },
]

# Add sequential problems
problems_data += [
    {
        'id': 'rising_edge_detector',
        'title': 'Rising Edge Detector',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['edge-detector', 'flip-flop', 'sequential'],
        'module_signature': 'module rising_edge_detector(input clk, input rst, input signal, output reg pulse);',
        'statement': 'Implement a rising edge detector that asserts a pulse for one cycle when the input transitions from 0 to 1 on the clock edge. The output must be synchronous and only high for a single clock cycle per rising edge. It must ignore level changes that do not occur on clock boundaries.',
        'behavior': ['pulse is 1 for exactly one clock cycle after signal rises from 0 to 1.', 'pulse is 0 otherwise.', 'rst clears internal state synchronously and sets pulse to 0.'],
        'constraints': 'Use sequential logic with registered state; do not use asynchronous edge detection macros.',
        'example': 'clk signal | pulse\n0 0 | 0\n1 1 | 1\n0 1 | 0',
        'hint': 'Store the previous input value and compare it to the current value on each clock.'
    },
    {
        'id': 'd_flipflop_sync_reset',
        'title': 'D Flip-Flop with Synchronous Reset',
        'difficulty': 'Easy',
        'category': 'Sequential',
        'tags': ['flip-flop', 'synchronous reset', 'register'],
        'module_signature': 'module d_flipflop_sync_reset(input clk, input rst, input d, output reg q);',
        'statement': 'Design a D flip-flop with synchronous active-high reset. On each rising clock edge, if reset is high the output should clear to zero; otherwise it should capture the D input. This is fundamental sequential storage for registered datapaths.',
        'behavior': ['On rising clock edge, if rst is high, q becomes 0.', 'If rst is low, q follows d on the clock edge.', 'No asynchronous reset or direct set is allowed.'],
        'constraints': 'Do not infer asynchronous behavior or use latches.',
        'example': 'clk rst d | q\n0 1 1 | 0\n1 0 1 | 1\n1 0 0 | 0',
        'hint': 'Use a clocked always block with rst in the sensitivity list for synchronous reset.'
    },
    {
        'id': 'johnson_counter_4bit',
        'title': '4-bit Johnson Counter',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['counter', 'shift-register', 'sequential'],
        'module_signature': 'module johnson_counter_4bit(input clk, input rst, output reg [3:0] q);',
        'statement': 'Implement a 4-bit Johnson counter that rotates inverted feedback through the register. On each clock edge the MSB is fed back inverted into the LSB, producing eight unique states. A synchronous reset should return the counter to 0000.',
        'behavior': ['q cycles through eight unique states with inverted feedback.', 'rst synchronously resets q to 0000.', 'Updates occur only on clock edges.'],
        'constraints': 'Do not use memory arrays or asynchronous logic.',
        'example': 'clk rst | q\n0 1 | 0000\n1 0 | 1000\n1 0 | 1100',
        'hint': 'Implement the register as a shift register with inverted MSB feedback.'
    },
    {
        'id': 'shift_register_8bit',
        'title': '8-bit Shift Register',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['shift-register', 'serial', 'sequential'],
        'module_signature': 'module shift_register_8bit(input clk, input rst, input serial_in, output reg [7:0] q);',
        'statement': 'Design an 8-bit shift register with serial input and parallel output. On each clock edge, the bits should shift one position toward the MSB, and the serial input should enter at the LSB. A synchronous clear should reset the register to zero.',
        'behavior': ['On rising clock, q shifts left by one with serial_in entering q[0].', 'rst synchronously clears q to 0.', 'The output q is updated only on clock edges.'],
        'constraints': 'Do not infer a combinational shift chain that bypasses the clock.',
        'example': 'clk rst serial_in | q\n0 1 0 | 00000000\n1 0 1 | 00000001\n1 0 0 | 00000010',
        'hint': 'Model the register as eight flip-flops updated in one clocked block.'
    },
    {
        'id': 'loadable_register',
        'title': 'Loadable Register',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['register', 'load enable', 'sequential'],
        'module_signature': 'module loadable_register(input clk, input rst, input load, input [7:0] d, output reg [7:0] q);',
        'statement': 'Create a loadable 8-bit register with enable and synchronous reset. When load is asserted on a clock edge, the register captures the input data; otherwise it retains its previous value. The reset input should clear the output to zero when asserted.',
        'behavior': ['If load is 1 on the rising edge, q <= d.', 'If load is 0, q holds its previous value.', 'rst synchronously clears q to 0.'],
        'constraints': 'Do not use asynchronous resets or combinational latches.',
        'example': 'clk rst load d    | q\n0 1 1 10101010 | 00000000\n1 0 1 10101010 | 10101010\n1 0 0 01010101 | 10101010',
        'hint': 'Use one always block with both clk and rst in the sensitivity list.'
    },
    {
        'id': 'up_down_counter',
        'title': 'Up/Down Counter',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['counter', 'bidirectional', 'sequential'],
        'module_signature': 'module up_down_counter(input clk, input rst, input dir, output reg [3:0] count);',
        'statement': 'Implement an up/down counter that increments or decrements a 4-bit value based on a direction input. On each clock edge it should count up when direction is 1 and down when direction is 0. A synchronous reset must set the counter to zero.',
        'behavior': ['If dir is 1, count increments on each clock edge.', 'If dir is 0, count decrements on each clock edge.', 'rst synchronously resets count to 0000.'],
        'constraints': 'Do not use asynchronous operations or parallel load features.',
        'example': 'clk rst dir | count\n0 1 0 | 0000\n1 0 1 | 0001\n1 0 0 | 0000',
        'hint': 'Implement count with straightforward increment/decrement logic and a reset branch.'
    },
    {
        'id': 'pulse_stretcher',
        'title': 'Pulse Stretcher',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['pulse', 'single-cycle', 'sequential'],
        'module_signature': 'module pulse_stretcher(input clk, input rst, input pulse_in, output reg pulse_out);',
        'statement': 'Design a pulse stretcher that extends a single-cycle input pulse on a 1-bit signal into a two-cycle output pulse. The module should assert the output for the cycle where the input pulse is detected and the following clock cycle. A synchronous reset clears the output and internal state to zero.',
        'behavior': ['pulse_out is high for two clock cycles after pulse_in is high for one cycle.', 'pulse_out is low when pulse_in is low and no stored extension exists.', 'rst synchronously clears pulse_out to 0.'],
        'constraints': 'Do not use asynchronous edge detection or latches.',
        'example': 'clk rst pulse_in | pulse_out\n0 1 0 | 0\n1 0 1 | 1\n1 0 0 | 1',
        'hint': 'Capture the pulse and use stored state to produce a second cycle of output.'
    },
    {
        'id': 'gated_d_latch',
        'title': 'Gated D Latch',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['latch', 'level-sensitive', 'sequential'],
        'module_signature': 'module gated_d_latch(input en, input d, output reg q);',
        'statement': 'Implement a gated D latch that transparently passes the input when enable is high and holds the value when enable is low. The latch must be level-sensitive, not edge-triggered, and must capture the input immediately while enabled. This is a basic storage element used in asynchronous design.',
        'behavior': ['When en is 1, q follows d continuously.', 'When en is 0, q retains its last value.', 'No clock input is permitted.'],
        'constraints': 'Do not infer an edge-triggered flip-flop or use clk signals.',
        'example': 'en d | q\n1 0 | 0\n1 1 | 1\n0 0 | 1',
        'hint': 'Use transparent latch behavior in a combinational feedback loop.'
    },
    {
        'id': 'clock_enable_register',
        'title': 'Clock-Enable Register',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['register', 'clock enable', 'sequential'],
        'module_signature': 'module clock_enable_register(input clk, input rst, input en, input [7:0] d, output reg [7:0] q);',
        'statement': 'Create an 8-bit register with a clock-enable signal that updates its output only when enable is high on a clock edge. When enable is low, the output remains unchanged. A synchronous reset should clear the register to zero.',
        'behavior': ['If en is 1 on the rising edge, q <= d.', 'If en is 0, q holds its value.', 'rst synchronously resets q to 0.'],
        'constraints': 'Do not use asynchronous reset or latches in the implementation.',
        'example': 'clk rst en d      | q\n0 1 0 10101010 | 00000000\n1 0 1 10101010 | 10101010\n1 0 0 01010101 | 10101010',
        'hint': 'A single clocked always block with conditional enable is enough.'
    },
    {
        'id': 'bit_pulse_generator',
        'title': 'Bit Pulse Generator',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['pulse', 'sequential', 'register'],
        'module_signature': 'module bit_pulse_generator(input clk, input rst, input in_bit, output reg pulse);',
        'statement': 'Implement a one-shot pulse generator that produces a single-cycle pulse whenever an input bit transitions from 0 to 1. The output must remain low otherwise and reset synchronously. This is useful for edge-triggered event capture in sequential logic.',
        'behavior': ['pulse is 1 for exactly one cycle after a rising transition.', 'pulse is 0 for all other cycles.', 'rst synchronously clears pulse to 0.'],
        'constraints': 'Do not use asynchronous edge detection or latches.',
        'example': 'in_bit | pulse\n0 0 1 | 1\n1 1 0 | 0',
        'hint': 'Store the previous sampled value and compare it to the current value.'
    },
    {
        'id': 'synchronous_clear_counter',
        'title': 'Synchronous Clear Counter',
        'difficulty': 'Easy',
        'category': 'Sequential',
        'tags': ['counter', 'reset', 'sequential'],
        'module_signature': 'module synchronous_clear_counter(input clk, input rst, input clear, output reg [3:0] count);',
        'statement': 'Design a 4-bit counter with synchronous clear that counts upward on each clock edge. When clear is asserted, the counter should reset to zero on the next clock. The counter must wrap around after 15 to 0.',
        'behavior': ['count increments by 1 each clock cycle when clear is 0.', 'If clear is 1 on a rising edge, count becomes 0.', 'rst synchronously resets count to 0.'],
        'constraints': 'Do not use asynchronous resets or latches.',
        'example': 'clk rst clear | count\n1 0 0 | 0001\n1 1 0 | 0000',
        'hint': 'Clock the counter and prioritize reset logic correctly.'
    },
    {
        'id': 'serial_to_parallel_register',
        'title': 'Serial-to-Parallel Register',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['shift-register', 'serialization', 'sequential'],
        'module_signature': 'module serial_to_parallel_register(input clk, input rst, input serial_in, input load, output reg [7:0] q);',
        'statement': 'Create a serial-to-parallel register that shifts in bits from serial_in on each clock and captures the result when load is asserted. The output holds the current parallel contents. A synchronous reset should clear the register to zero.',
        'behavior': ['On each rising edge, q shifts left and serial_in enters q[0].', 'If load is asserted, q presents the accumulated parallel word.', 'rst synchronously clears q to 0.'],
        'constraints': 'Do not use asynchronous or combinational latches.',
        'example': 'clk rst serial_in | q\n1 0 1 | 00000001\n1 0 0 | 00000010',
        'hint': 'Use a shift register and a load condition in the clocked block.'
    },
    {
        'id': 'debounce_filter',
        'title': 'Debounce Filter',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['debounce', 'filter', 'sequential'],
        'module_signature': 'module debounce_filter(input clk, input rst, input noisy, output reg clean);',
        'statement': 'Implement a debounce filter that only changes output after the input has remained stable for two consecutive clock cycles. This suppresses mechanical switch bounce. A synchronous reset must initialize the clean output to zero.',
        'behavior': ['clean changes only when noisy remains stable for two cycles.', 'clean holds its previous value during instability.', 'rst synchronously clears clean to 0.'],
        'constraints': 'Do not infer latches or asynchronous glitch detectors.',
        'example': 'noisy clean\n0 0\n1 0\n1 1',
        'hint': 'Store the previous input sample and require agreement across two cycles.'
    },
    {
        'id': 'traffic_light_fsm',
        'title': 'Traffic Light FSM',
        'difficulty': 'Medium',
        'category': 'FSM',
        'tags': ['traffic light', 'moore', 'fsm'],
        'module_signature': 'module traffic_light_fsm(input clk, input rst, output reg red, output reg green, output reg yellow);',
        'statement': 'Design a 3-state traffic light controller that cycles through Red, Green, and Yellow on each clock edge. The controller should spend one cycle in each state and then transition to the next in the sequence Red -> Green -> Yellow -> Red. A synchronous reset should force the controller to Red.',
        'behavior': ['Only one of red, green, or yellow may be asserted at a time.', 'The state sequence is Red, Green, Yellow, then back to Red.', 'rst synchronously forces the state to Red.'],
        'constraints': 'Do not infer latches or asynchronous state changes.',
        'example': 'state | red green yellow\nRed   | 1 0 0\nGreen | 0 1 0\nYellow| 0 0 1',
        'hint': 'Implement a Moore FSM where outputs depend only on the current state.'
    },
    {
        'id': 'vending_machine_controller',
        'title': 'Vending Machine Controller',
        'difficulty': 'Hard',
        'category': 'FSM',
        'tags': ['fsm', 'controller', 'state-machine'],
        'module_signature': 'module vending_machine_controller(input clk, input rst, input coin5, input coin10, output reg dispense);',
        'statement': 'Build a simple vending machine controller that accepts coins of 5 and 10 units and dispenses a product when at least 15 units are inserted. It must maintain accumulated credit across clock cycles and produce a pulse when the product is ready. A synchronous reset should clear the stored credit.',
        'behavior': ['Track the inserted amount and dispense when credit >= 15.', 'dispense pulses high for one cycle when product is released.', 'rst synchronously resets the stored credit to zero.'],
        'constraints': 'Do not use asynchronous counters or unclocked state storage.',
        'example': 'coin5 coin10 | dispense\n0 1      | 0\n1 0      | 0\n1 1      | 1',
        'hint': 'Use an FSM with a small credit accumulator and transitions for each coin type.'
    },
    {
        'id': 'pedestrian_crossing_controller',
        'title': 'Pedestrian Crossing Controller',
        'difficulty': 'Medium',
        'category': 'FSM',
        'tags': ['fsm', 'controller', 'safety'],
        'module_signature': 'module pedestrian_crossing_controller(input clk, input rst, input walk_request, output reg vehicle_green, output reg vehicle_yellow, output reg vehicle_red, output reg walk);',
        'statement': 'Design a pedestrian crossing controller that waits in a default vehicle-green state and responds to a walk request. When the request is asserted, the controller must transition through vehicle-yellow then vehicle-red before asserting walk. The walk output should be active for one cycle and the controller should then return to vehicle-green after a short delay.',
        'behavior': ['Normal operation remains in vehicle_green until walk_request arrives.', 'The controller transitions through yellow and red before asserting walk.', 'walk is asserted only during the dedicated pedestrian phase.'],
        'constraints': 'Do not use combinational loops or latches.',
        'example': 'state | vehicle_green vehicle_yellow vehicle_red walk\nIdle  | 1 0 0 0\nWalk  | 0 0 1 1',
        'hint': 'Model the sequence with named states and a state register.'
    },
    {
        'id': 'elevator_floor_controller',
        'title': 'Elevator Floor Controller',
        'difficulty': 'Hard',
        'category': 'FSM',
        'tags': ['fsm', 'controller', 'priority'],
        'module_signature': 'module elevator_floor_controller(input clk, input rst, input request_up, input request_down, output reg [1:0] floor, output reg moving_up, output reg moving_down);',
        'statement': 'Implement a simplified elevator controller for three floors. It should respond to up/down requests and move between floors until the requested floor is reached. The controller must express the current floor and motion state in outputs and use a synchronous reset to return to floor 1.',
        'behavior': ['floor encodes the current floor number between 1 and 3.', 'moving_up or moving_down indicates the current direction.', 'rst synchronously returns the elevator to floor 1 idle.'],
        'constraints': 'Do not use memory arrays or asynchronous state inference.',
        'example': 'request_up request_down | floor moving_up moving_down\n1 0 | 10 1 0\n0 1 | 01 0 1',
        'hint': 'Use a finite set of states to represent floor and motion.'
    },
    {
        'id': 'bus_arbiter',
        'title': 'Round-Robin Bus Arbiter',
        'difficulty': 'Hard',
        'category': 'FSM',
        'tags': ['arbiter', 'round-robin', 'fsm'],
        'module_signature': 'module bus_arbiter(input clk, input rst, input [2:0] req, output reg [2:0] grant);',
        'statement': 'Create a 3-master round-robin bus arbiter that grants access in a fair rotating order. When one master requests the bus, grant it and rotate priority to the next master on the following cycle. If no requests are active, all grants must be deasserted.',
        'behavior': ['One grant at most may be active when requests are present.', 'Grant rotates priority fairly among requesting masters.', 'rst synchronously returns priority to master 0.'],
        'constraints': 'Do not use asynchronous priority encoders or memory arrays.',
        'example': 'req grant\n001 001\n011 010\n111 100',
        'hint': 'Use state to remember the next master to serve after each grant.'
    },
    {
        'id': 'serial_frame_detector',
        'title': 'Serial Frame Detector',
        'difficulty': 'Hard',
        'category': 'FSM',
        'tags': ['fsm', 'serial', 'pattern-detect'],
        'module_signature': 'module serial_frame_detector(input clk, input rst, input serial_in, output reg frame_valid);',
        'statement': 'Design an FSM that detects the start and stop framing of a simple serial protocol with one start bit (0), eight data bits, and one stop bit (1). The module should assert a frame_valid pulse when a complete valid frame is received. A synchronous reset clears the detector state.',
        'behavior': ['frame_valid pulses high for one cycle after a correctly framed byte.', 'A valid frame begins with 0 and ends with 1.', 'rst synchronously returns the FSM to idle state.'],
        'constraints': 'Do not use unclocked shift registers or combinational frame detection.',
        'example': 'serial_in | frame_valid\n0 1 0 1 1 | 1',
        'hint': 'Track the expected position within the frame using FSM states.'
    },
    {
        'id': 'handshake_controller',
        'title': 'Four-Phase Handshake Controller',
        'difficulty': 'Medium',
        'category': 'FSM',
        'tags': ['handshake', 'fsm', 'control'],
        'module_signature': 'module handshake_controller(input clk, input rst, input req, output reg ack);',
        'statement': 'Implement a four-phase request/acknowledge handshake controller. When req is asserted, the controller should assert ack after one cycle and then wait for req to deassert before releasing ack. The controller must return to idle only after both signals have completed the handshake cycle.',
        'behavior': ['ack is asserted only while the request is active and the handshake is in progress.', 'The system waits for req to deassert before deasserting ack.', 'rst synchronously resets the controller to idle.'],
        'constraints': 'Do not use latches or asynchronous feedback loops.',
        'example': 'req ack\n1 0 | 1\n0 1 | 0',
        'hint': 'Use explicit states for idle, wait-for-ack, and return-to-idle.'
    },
    {
        'id': 'thermal_shutdown_fsm',
        'title': 'Thermal Shutdown FSM',
        'difficulty': 'Hard',
        'category': 'FSM',
        'tags': ['fsm', 'safety', 'threshold'],
        'module_signature': 'module thermal_shutdown_fsm(input clk, input rst, input [7:0] temp, output reg fan_enable);',
        'statement': 'Create a thermal shutdown controller that disables an output when temperature exceeds a threshold and re-enables it only after the temperature drops below a lower hysteresis threshold. The output must not chatter when temperature hovers near the boundary. A synchronous reset should immediately disable the output.',
        'behavior': ['fan_enable is 0 when temp >= 100.', 'fan_enable remains 1 until temp drops below 90.', 'rst synchronously disables the fan_enable output.'],
        'constraints': 'Do not use combinational hysteresis or latches.',
        'example': 'temp fan_enable\n100 0\n095 1\n099 0',
        'hint': 'Use separate states for enabled and disabled conditions with hysteresis boundaries.'
    },
    {
        'id': 'simple_alu_8bit',
        'title': 'Simple ALU',
        'difficulty': 'Hard',
        'category': 'Arithmetic',
        'tags': ['alu', 'opcode', 'arithmetic'],
        'module_signature': 'module simple_alu_8bit(input [7:0] a, input [7:0] b, input [2:0] op, output reg [7:0] result, output reg zero);',
        'statement': 'Design an 8-bit ALU that performs add, subtract, AND, OR, and NOT operations selected by a 3-bit opcode. The module must produce a valid result for every opcode and handle two’s complement subtraction correctly. The NOT operation should apply only to operand a while ignoring operand b.',
        'behavior': ['op=000: result = a + b.', 'op=001: result = a - b.', 'op=010: result = a & b, 011: a | b, 100: ~a.', 'zero is 1 when result == 0.'],
        'constraints': 'Do not use behavioral arrays or function calls for operation selection.',
        'example': 'a b op | result zero\n00000001 00000010 000 | 00000011 0\n00000101 00000011 001 | 00000010 0\n11111111 00000000 100 | 00000000 1',
        'hint': 'Implement each operation explicitly and choose with a case statement.'
    },
    {
        'id': 'ripple_carry_adder',
        'title': 'Ripple Carry Adder',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['adder', 'ripple', 'arithmetic'],
        'module_signature': 'module ripple_carry_adder(input [7:0] a, input [7:0] b, input cin, output [7:0] sum, output cout);',
        'statement': 'Implement an 8-bit ripple carry adder with carry-in and carry-out. The module must compute the full sum of two operands plus the carry-in, producing the lower 8 bits and a carry-out. This is the classic serialized carry-chain adder used in basic ALU datapaths.',
        'behavior': ['sum = a + b + cin modulo 256.', 'cout is the carry-out of the addition.', 'No sequential state is permitted.'],
        'constraints': 'Do not use the + operator for the entire 8-bit vector if you want a structural solution.',
        'example': 'a b cin | sum cout\n00000001 00000001 0 | 00000010 0\n11111111 00000001 0 | 00000000 1',
        'hint': 'Build the adder from full-adders or use vector addition directly with carry.'
    },
    {
        'id': 'carry_lookahead_adder',
        'title': 'Carry Lookahead Adder',
        'difficulty': 'Hard',
        'category': 'Arithmetic',
        'tags': ['adder', 'carry-lookahead', 'arithmetic'],
        'module_signature': 'module carry_lookahead_adder(input [7:0] a, input [7:0] b, input cin, output [7:0] sum, output cout);',
        'statement': 'Build an 8-bit carry lookahead adder module that computes group generate and propagate signals to accelerate carry calculations. The adder must produce correct sum and carry-out values while using these faster carry terms. This design is used in higher-performance arithmetic units.',
        'behavior': ['sum = a + b + cin.', 'cout is the final carry-out.', 'Use carry lookahead logic to compute carries efficiently.'],
        'constraints': 'Do not implement it as a simple ripple-carry adder.',
        'example': 'a b cin | sum cout\n00000001 00000001 0 | 00000010 0\n11110000 00001111 1 | 00000000 1',
        'hint': 'Compute generate/propagate bits to avoid sequential carry propagation.'
    },
    {
        'id': 'saturating_adder',
        'title': 'Saturating Adder',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['saturating', 'adder', 'arithmetic'],
        'module_signature': 'module saturating_adder(input signed [7:0] a, input signed [7:0] b, output reg signed [7:0] y);',
        'statement': 'Design an 8-bit saturating adder that clamps results to the maximum or minimum signed value on overflow. If signed addition overflows positively, output 01111111; if it overflows negatively, output 10000000. No overflow flag is required, only the saturated result.',
        'behavior': ['y = a + b unless the signed result overflows.', 'Positive overflow saturates to 127.', 'Negative overflow saturates to -128.'],
        'constraints': 'Do not use behavioral arithmetic that ignores overflow semantics.',
        'example': 'a b | y\n01111111 00000001 | 01111111\n10000000 10000000 | 10000000',
        'hint': 'Detect overflow from the sign bits of operands and result.'
    },
]

problems_data += [
    {
        'id': 'overflow_detector',
        'title': 'Signed Overflow Detector',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['overflow', 'detector', 'arithmetic'],
        'module_signature': 'module overflow_detector(input signed [7:0] a, input signed [7:0] b, input signed [7:0] sum, output overflow);',
        'statement': 'Create a signed overflow detector for 8-bit addition. The module should assert overflow whenever two operands and the result violate signed overflow rules. This is a common condition check in ALUs and arithmetic pipelines.',
        'behavior': ['overflow is 1 when adding a and b produces a signed result outside [-128, 127].', 'overflow is 0 for all other cases.', 'Outputs must be purely combinational.'],
        'constraints': 'Do not use registers or sequential logic.',
        'example': 'a b sum | overflow\n01111111 00000001 10000000 | 1\n10000000 10000000 00000000 | 1\n00000001 00000001 00000010 | 0',
        'hint': 'Check if the operands have the same sign and the result has a different sign.'
    },
    {
        'id': 'unsigned_multiplier_4x4',
        'title': '4x4 Unsigned Multiplier',
        'difficulty': 'Hard',
        'category': 'Arithmetic',
        'tags': ['multiplier', 'datapath', 'arithmetic'],
        'module_signature': 'module unsigned_multiplier_4x4(input [3:0] a, input [3:0] b, output [7:0] product);',
        'statement': 'Implement a 4x4 unsigned multiplier that produces an 8-bit product for two 4-bit operands. The module must be purely combinational and suitable for use in a small datapath block. This exercise covers boolean multiplication and partial product accumulation.',
        'behavior': ['product = a * b.', 'All outputs must update combinationally.', 'No sequential or registered logic may be used.'],
        'constraints': 'Do not use behavioral loops to build the multiplier if you want a structural solution.',
        'example': 'a b | product\n0011 0101 | 00001111\n1111 1111 | 11100001',
        'hint': 'Think of partial products and addition of shifted terms.'
    },
    {
        'id': 'conditional_incrementer',
        'title': 'Conditional Incrementer',
        'difficulty': 'Easy',
        'category': 'Arithmetic',
        'tags': ['incrementer', 'arithmetic', 'combinational'],
        'module_signature': 'module conditional_incrementer(input [7:0] a, input enable, output [7:0] y);',
        'statement': 'Build an 8-bit conditional incrementer that adds 1 to the operand when enable is high, and otherwise passes the operand unchanged. The output must be stable combinationally and must not use storage elements. This supports increment-by-one operations in datapath circuits.',
        'behavior': ['If enable is 1, y = a + 1.', 'If enable is 0, y = a.', 'The implementation must be combinational.'],
        'constraints': 'Avoid clocked predicates or registers.',
        'example': 'a enable | y\n00000000 1 | 00000001\n11111111 1 | 00000000\n01010101 0 | 01010101',
        'hint': 'Use addition only when enable is asserted.'
    },
    {
        'id': 'sign_magnitude_comparator',
        'title': 'Signed Magnitude Comparator',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['comparator', 'signed', 'arithmetic'],
        'module_signature': 'module sign_magnitude_comparator(input signed [7:0] a, input signed [7:0] b, output gt, output eq, output lt);',
        'statement': 'Design a signed magnitude comparator that compares two 8-bit values treated as signed integers. The outputs should indicate greater-than, equal, and less-than relationships in signed two’s complement form. The comparator should work for negative and positive operands.',
        'behavior': ['gt is 1 when a > b as signed numbers.', 'eq is 1 when a == b.', 'lt is 1 when a < b.'],
        'constraints': 'Do not use sequential logic or internal registers.',
        'example': 'a b | gt eq lt\n00000001 00000010 | 0 0 1\n11111111 00000001 | 0 0 1\n10000000 01111111 | 0 0 1',
        'hint': 'Signed comparison is different from unsigned comparison when the sign bits differ.'
    },
    {
        'id': 'saturating_subtractor',
        'title': 'Saturating Subtractor',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['subtractor', 'saturating', 'arithmetic'],
        'module_signature': 'module saturating_subtractor(input signed [7:0] a, input signed [7:0] b, output reg signed [7:0] y);',
        'statement': 'Implement an 8-bit saturating subtractor that clamps the signed result at -128 or +127 on overflow. The subtractor should compute a - b and saturate the result when the signed difference exceeds representable bounds. This prevents wraparound in arithmetic datapaths.',
        'behavior': ['y = a - b unless signed overflow occurs.', 'Positive overflow saturates to 127.', 'Negative overflow saturates to -128.'],
        'constraints': 'Do not use behavioral constructs that ignore signed overflow semantics.',
        'example': 'a b | y\n01111111 11111111 | 01111111\n10000000 00000001 | 10000000',
        'hint': 'Detect signed overflow by comparing operand signs and result signs.'
    },
    {
        'id': 'multiplier_accumulator',
        'title': 'Multiplier Accumulator',
        'difficulty': 'Hard',
        'category': 'Arithmetic',
        'tags': ['multiplier', 'accumulator', 'arithmetic'],
        'module_signature': 'module multiplier_accumulator(input clk, input rst, input en, input [3:0] a, input [3:0] b, output reg [7:0] acc);',
        'statement': 'Build a 4-bit multiplier-accumulator that multiplies two 4-bit unsigned operands and adds the result to an 8-bit accumulator. The accumulator must update on a clock edge and support synchronous reset. This unit is common in DSP datapaths.',
        'behavior': ['When en is 1, acc <= acc + (a * b) on the rising edge.', 'If en is 0, acc retains its value.', 'rst synchronously clears acc to 0.'],
        'constraints': 'Do not use asynchronous reset or combinational accumulation.',
        'example': 'clk rst en a b | acc\n0 1 0 xx | 00000000\n1 0 1 0011 0010 | 00000110',
        'hint': 'Use a register for acc and compute the product combinationally.'
    },
    {
        'id': 'fixed_point_multiplier',
        'title': 'Fixed-Point Multiplier',
        'difficulty': 'Hard',
        'category': 'Arithmetic',
        'tags': ['fixed-point', 'multiplier', 'arithmetic'],
        'module_signature': 'module fixed_point_multiplier(input signed [7:0] a, input signed [7:0] b, output signed [15:0] product);',
        'statement': 'Implement a fixed-point multiplier that multiplies two signed 8-bit values and produces a 16-bit signed product. The module must preserve two’s complement behavior across the full range. This block is used in DSP datapaths for fractional arithmetic.',
        'behavior': ['product = a * b with signed two’s complement semantics.', 'All outputs must update combinationally.', 'Avoid sequential storage in the multiplier logic.'],
        'constraints': 'Do not use clocked registers or behavioral saturation.',
        'example': 'a b | product\n00000001 00000010 | 0000000000000010\n11111111 00000001 | 1111111111111111',
        'hint': 'Treat the inputs as signed and use full-width product arithmetic.'
    },
    {
        'id': 'absolute_difference',
        'title': 'Absolute Difference',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['difference', 'absolute', 'arithmetic'],
        'module_signature': 'module absolute_difference(input [7:0] a, input [7:0] b, output reg [7:0] diff);',
        'statement': 'Design a unit that computes the absolute difference between two unsigned 8-bit values. The output should always be nonnegative and equal to |a - b|. This combinational block is useful in error detection and distance metrics.',
        'behavior': ['diff equals a - b when a >= b.', 'diff equals b - a when b > a.', 'Output must be nonnegative and unsigned.'],
        'constraints': 'Do not use sequential storage or clocks.',
        'example': 'a b | diff\n00000100 00000011 | 00000001\n00000010 00000100 | 00000010',
        'hint': 'Use a comparator to choose the subtraction direction.'
    },
    {
        'id': 'compare_select',
        'title': 'Compare-and-Select Unit',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['select', 'comparator', 'arithmetic'],
        'module_signature': 'module compare_select(input [7:0] a, input [7:0] b, input sel, output reg [7:0] y);',
        'statement': 'Create a compare-and-select unit that outputs either the smaller or larger of two unsigned values based on a select signal. When sel is 0 the module outputs the smaller value, and when sel is 1 it outputs the larger value. This block is useful in conditional datapath steering.',
        'behavior': ['When sel is 0, y = min(a,b).', 'When sel is 1, y = max(a,b).', 'If values are equal, output may be either value.'],
        'constraints': 'Do not use sequential or clocked logic.',
        'example': 'a b sel | y\n00000010 00000100 0 | 00000010\n00000010 00000100 1 | 00000100',
        'hint': 'Compare a and b and use the select signal to choose the result.'
    },
]

problems_data += [
    {
        'id': 'fifo_sync_8x8',
        'title': 'Synchronous FIFO',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['fifo', 'memory', 'sequential'],
        'module_signature': 'module fifo_sync_8x8(input clk, input rst, input write_en, input read_en, input [7:0] din, output reg [7:0] dout, output reg full, output reg empty);',
        'statement': 'Implement a synchronous FIFO with 8 entries of 8-bit width and separate read/write ports. The module should support push and pop operations, report full and empty conditions, and store data in internal memory. The FIFO must prevent reads when empty and writes when full, while preserving first-in, first-out order.',
        'behavior': ['write_en stores din into the FIFO when full is 0.', 'read_en outputs the next stored value when empty is 0.', 'full and empty reflect the current FIFO status.'],
        'constraints': 'Do not use external memory macros; implement storage internally.',
        'example': 'write_en read_en | full empty dout\n1 0 | 0 0 xx\n0 1 | 0 0 stored',
        'hint': 'Use a circular buffer with separate write and read pointers.'
    },
    {
        'id': 'register_file_8x8_2r1w',
        'title': '8-Register File: 2 Read Ports, 1 Write Port',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['register-file', 'memory', 'datapath'],
        'module_signature': 'module register_file_8x8_2r1w(input clk, input rst, input write_en, input [2:0] write_addr, input [7:0] write_data, input [2:0] read_addr_a, input [2:0] read_addr_b, output [7:0] read_data_a, output [7:0] read_data_b);',
        'statement': 'Design an 8-register file with two asynchronous read ports and one synchronous write port. Reads should return the contents of addressed registers immediately, while writes occur on the clock edge. A synchronous reset should clear all registers to zero.',
        'behavior': ['read_data_a and read_data_b reflect the contents at the read addresses.', 'write occurs on the rising edge when write_en is 1.', 'rst synchronously clears all registers to zero.'],
        'constraints': 'Do not use asynchronous writes or multi-clock memories.',
        'example': 'write_en write_addr write_data | read_addr_a read_data_a\n1 010 00001111 | 010 00001111',
        'hint': 'Implement the register file as an array of flip-flops indexed by address.'
    },
    {
        'id': 'sram_1kx8',
        'title': 'SRAM Behavioral Model',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['sram', 'behavioral', 'memory'],
        'module_signature': 'module sram_1kx8(input clk, input rst, input wr_en, input [9:0] addr, input [7:0] din, output reg [7:0] dout);',
        'statement': 'Create a simple 1Kx8 SRAM behavioral model with separate read and write enable signals. Reads should output the stored byte at the addressed location, and writes should update memory on the clock edge when write enable is asserted. The design should model synchronous writes and asynchronous reads typical of embedded SRAM.',
        'behavior': ['dout reflects the contents at addr.', 'Writes occur on the rising edge when wr_en is 1.', 'rst may synchronously clear a subset of memory if desired.'],
        'constraints': 'Do not instantiate vendor-specific RAM primitives.',
        'example': 'addr wr_en din | dout\n0000000000 0 xx | stored\n0000000001 1 01010101 | 01010101',
        'hint': 'Use a reg array to model the memory contents.'
    },
    {
        'id': 'dual_port_ram',
        'title': 'Dual-Port RAM',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['ram', 'dual-port', 'memory'],
        'module_signature': 'module dual_port_ram(input clk, input wr_en, input [3:0] wr_addr, input [7:0] wr_data, input [3:0] rd_addr, output reg [7:0] rd_data);',
        'statement': 'Build a true dual-port RAM with two independent read/write ports sharing the same memory array. One port should support read operations and the other should support writes simultaneously. The module must prevent write collisions by requiring that both ports do not write the same address at the same time.',
        'behavior': ['rd_data returns the value stored at rd_addr.', 'Writes update the memory on the rising edge when wr_en is 1.', 'No two writes may attempt the same address simultaneously.'],
        'constraints': 'Do not use behavioral arrays that infer dual-port conflict resolution automatically.',
        'example': 'wr_en wr_addr wr_data | rd_addr rd_data\n1 0001 10101010 | 0001 10101010',
        'hint': 'Implement a single memory array and separate logic for read/write ports.'
    },
    {
        'id': 'memory_arbiter_3to1',
        'title': 'Memory Arbiter',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['arbiter', 'memory', 'sequential'],
        'module_signature': 'module memory_arbiter_3to1(input clk, input rst, input [2:0] req, output reg [2:0] grant);',
        'statement': 'Design a memory arbiter that grants one of three requesters access to a shared memory bus based on fixed priority. The highest-priority request should be granted while lower priorities wait. The grant state should be maintained until the active request releases the bus.',
        'behavior': ['Only one grant may be asserted at a time.', 'Grants follow fixed priority from req[2] down to req[0].', 'rst synchronously deasserts all grants.'],
        'constraints': 'Do not use asynchronous priority encoders that bypass state.',
        'example': 'req grant\n100 100\n010 010\n001 001',
        'hint': 'Use registered grant outputs and update them on the clock edge.'
    },
    {
        'id': 'shared_register_file',
        'title': 'Shared Register File',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['register-file', 'memory', 'datapath'],
        'module_signature': 'module shared_register_file(input clk, input rst, input write_en, input [2:0] write_addr, input [7:0] write_data, input [2:0] read_addr_a, input [2:0] read_addr_b, output [7:0] read_data_a, output [7:0] read_data_b);',
        'statement': 'Create a shared register file with one write port and two read ports that arbitrates competing read requests. When both reads request the same address, the module should still return the correct data on both outputs. Writes occur synchronously on the clock edge.',
        'behavior': ['Simultaneous reads of the same address return the same value.', 'Writes happen on the rising edge when write_en is 1.', 'rst synchronously clears all registers.'],
        'constraints': 'Avoid multi-clock or asynchronous write semantics.',
        'example': 'write_addr read_addr_a read_addr_b | read_data_a read_data_b\n010 010 011 | val val2',
        'hint': 'Use a storage array with combinational read ports.'
    },
    {
        'id': 'circular_buffer',
        'title': 'Circular Buffer',
        'difficulty': 'Medium',
        'category': 'Memory',
        'tags': ['fifo', 'buffer', 'memory'],
        'module_signature': 'module circular_buffer(input clk, input rst, input push, input pop, input [7:0] din, output reg [7:0] dout, output reg full, output reg empty);',
        'statement': 'Implement an 8-entry circular buffer with a write pointer and a read pointer. Writes should wrap back to the first entry after the last, and reads should return the oldest stored value. The buffer should include full and empty flags.',
        'behavior': ['push writes data when full is 0.', 'pop reads data when empty is 0.', 'full and empty indicate buffer status.'],
        'constraints': 'Do not use built-in queue primitives.',
        'example': 'push pop | full empty dout\n1 0 | 0 0 xx\n0 1 | 0 0 stored',
        'hint': 'Maintain separate counters for entries and wrap pointer values.'
    },
    {
        'id': 'write_back_buffer',
        'title': 'Write-Back Buffer',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['buffer', 'write-back', 'memory'],
        'module_signature': 'module write_back_buffer(input clk, input rst, input wr_en, input [3:0] addr, input [7:0] data_in, input rd_en, input [3:0] rd_addr, output reg [7:0] data_out, output reg pending);',
        'statement': 'Design a write-back buffer that holds one pending write and forwards reads to the updated value when necessary. When a write is pending and a read targets the same address, the buffered value should be returned instead of the older memory value. The buffer should commit data on the next clock cycle.',
        'behavior': ['pending is 1 when a write is staged but not yet committed.', 'Reads to the pending address return the buffered data.', 'rst clears the pending buffer state.'],
        'constraints': 'Do not use actual external memory primitives; model the buffer behavior explicitly.',
        'example': 'wr_en addr data_in rd_en rd_addr | pending data_out\n1 0010 10101010 1 0010 | 1 10101010',
        'hint': 'Track the pending address and data separately from the memory array.'
    },
    {
        'id': 'cache_line_buffer',
        'title': 'Cache Line Buffer',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['cache', 'buffer', 'memory'],
        'module_signature': 'module cache_line_buffer(input clk, input rst, input [1:0] index, input [7:0] tag, input [15:0] data_in, input write_en, output reg [15:0] data_out, output reg hit);',
        'statement': 'Create a simple 4-line cache buffer that stores 16-bit tag/data pairs and supplies data on hits. The module should check tags for a hit and output valid data only on hits. A miss is indicated by valid being low.',
        'behavior': ['hit is 1 when the requested tag matches the stored tag at index.', 'data_out holds valid data only on a hit.', 'rst invalidates all cache lines.'],
        'constraints': 'Do not use built-in cache or associative memory primitives.',
        'example': 'index tag write_en | hit data_out\n00 00000001 0 | 0 xxxx\n01 00000010 1 | 0 data',
        'hint': 'Store separate tag and data arrays with enable control.'
    },
    {
        'id': 'banked_register_file',
        'title': 'Banked Register File',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['register-file', 'banked', 'memory'],
        'module_signature': 'module banked_register_file(input clk, input rst, input write_en, input bank_sel, input [2:0] write_addr, input [7:0] write_data, input [2:0] read_addr_a, input [2:0] read_addr_b, output [7:0] read_data_a, output [7:0] read_data_b);',
        'statement': 'Implement a banked register file with two 8-entry banks and one write port. The bank select signal chooses which bank receives writes. Reads should return values from both banks simultaneously on separate outputs.',
        'behavior': ['write_data is stored in the selected bank when write_en is 1.', 'read_data_a and read_data_b reflect their respective bank values.', 'rst synchronously clears both banks.'],
        'constraints': 'Do not use vendor-specific multi-bank memory macros.',
        'example': 'bank_sel write_en write_addr | read_data_a\n0 1 010 | data',
        'hint': 'Model each bank as an independent register array.'
    },
    {
        'id': 'pointer_based_buffer',
        'title': 'Pointer-Based Buffer',
        'difficulty': 'Medium',
        'category': 'Memory',
        'tags': ['buffer', 'pointer', 'memory'],
        'module_signature': 'module pointer_based_buffer(input clk, input rst, input write_en, input read_en, input [7:0] din, output reg [7:0] dout, output reg full, output reg empty);',
        'statement': 'Design a 4-entry buffer with separate write and read pointers and full/empty indicators. Writes should advance the write pointer and reads advance the read pointer on the clock. The buffer must be circular and handle simultaneous write/read correctly.',
        'behavior': ['write_en stores din when full is 0.', 'read_en outputs the next value when empty is 0.', 'full/empty flags indicate buffer status.'],
        'constraints': 'Do not use external queue primitives.',
        'example': 'write_en read_en | full empty dout\n1 0 | 0 0 xx\n0 1 | 0 0 stored',
        'hint': 'Maintain write/read pointers and count entries.'
    },
    {
        'id': 'single_port_ram_16x8',
        'title': 'Single-Port RAM',
        'difficulty': 'Medium',
        'category': 'Memory',
        'tags': ['ram', 'single-port', 'memory'],
        'module_signature': 'module single_port_ram_16x8(input clk, input rst, input wr_en, input [3:0] addr, input [7:0] din, output reg [7:0] dout);',
        'statement': 'Implement a single-port RAM with 16 entries of 8-bit width. Writes should occur on the rising edge when wr_en is asserted, and reads should output the current value at addr. A synchronous reset should clear all memory entries.',
        'behavior': ['Writes update memory on the clock edge when wr_en is 1.', 'dout reflects the current contents at addr.', 'rst clears all memory to 0 synchronously.'],
        'constraints': 'Do not use vendor-specific memory primitives.',
        'example': 'addr wr_en din | dout\n0000 0 xx | stored\n0001 1 10101010 | 10101010',
        'hint': 'Use a reg array and clocked write logic.'
    },
    {
        'id': 'read_after_write_buffer',
        'title': 'Read-After-Write Buffer',
        'difficulty': 'Hard',
        'category': 'Memory',
        'tags': ['buffer', 'hazard', 'memory'],
        'module_signature': 'module read_after_write_buffer(input clk, input rst, input wr_en, input [3:0] addr, input [7:0] data_in, input rd_en, input [3:0] rd_addr, output reg [7:0] data_out);',
        'statement': 'Design a read-after-write buffer that forwards the most recent write value to reads of the same address before the write commits to memory. The module should support synchronous writes and combinational reads with forwarding. This avoids stale data hazards in simple memory systems.',
        'behavior': ['If a pending write matches rd_addr, data_out returns the new write data.', 'Otherwise, data_out returns the stored memory value.', 'rst clears pending writes and memory contents.'],
        'constraints': 'Do not use implicit vendor forward logic or asynchronous memory primitives.',
        'example': 'wr_en addr data_in rd_en rd_addr | data_out\n1 0010 10101010 1 0010 | 10101010',
        'hint': 'Track the pending write address and data separately.'
    },
]

problems_data += [
    {
        'id': 'barrel_shifter_32bit',
        'title': '32-bit Barrel Shifter',
        'difficulty': 'Hard',
        'category': 'Datapath',
        'tags': ['shifter', 'datapath', 'logical-shift'],
        'module_signature': 'module barrel_shifter_32bit(input [31:0] a, input [4:0] shamt, input dir, output [31:0] y);',
        'statement': 'Implement a 32-bit barrel shifter that performs logical left and logical right shifts based on a direction input. The shift amount is a 5-bit value from 0 to 31. The module should be combinational and preserve zeros in vacated bit positions.',
        'behavior': ['If dir is 0, shift a left by shamt bits logically.', 'If dir is 1, shift a right by shamt bits logically.', 'Shifted-in positions must be zeros.'],
        'constraints': 'Do not use registers or sequential shifting operations.',
        'example': 'a shamt dir | y\n00000001 00001 0 | 00000010\n00000001 00001 1 | 00000000',
        'hint': 'Use nested conditional assignments for the shift amount.'
    },
    {
        'id': 'alu_with_flags',
        'title': 'ALU with Flags',
        'difficulty': 'Hard',
        'category': 'Datapath',
        'tags': ['alu', 'flags', 'datapath'],
        'module_signature': 'module alu_with_flags(input [7:0] a, input [7:0] b, input [2:0] op, output reg [7:0] result, output reg zero, output reg negative, output reg carry);',
        'statement': 'Design an 8-bit ALU that performs add, subtract, AND, OR, and XOR operations and also generates zero, negative, and carry flags. The flags should reflect the result of the selected operation. This module is a key datapath component in a microprocessor.',
        'behavior': ['result reflects the selected arithmetic or logical operation.', 'zero is 1 when result is 0.', 'negative is 1 when result[7] is 1.', 'carry is 1 for unsigned addition or subtraction carry/borrow.'],
        'constraints': 'Do not use sequential registers beyond output registers assigned in combinational logic.',
        'example': 'a b op | result zero negative carry\n00000001 00000001 000 | 00000010 0 0 0',
        'hint': 'Compute all operation results and then select the appropriate one.'
    },
    {
        'id': 'sign_extension_datapath',
        'title': 'Sign Extension Datapath Block',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['sign-extension', 'datapath', 'combinational'],
        'module_signature': 'module sign_extension_datapath(input [6:0] a, output [15:0] y);',
        'statement': 'Create a datapath block that sign-extends a 7-bit signed input to 16 bits and then adds a constant offset of 8. The result should be a signed 16-bit value. This illustrates how sign extension is integrated into a datapath before arithmetic.',
        'behavior': ['Extend a to 16 bits preserving sign from a[6].', 'Add a constant 8 to the extended value.', 'The module must be purely combinational.'],
        'constraints': 'Do not use sequential storage or multiple clock domains.',
        'example': 'a     | y\n1000000 | 11111111_11111000\n0111111 | 00000000_10000111',
        'hint': 'First extend the sign bit then perform addition.'
    },
    {
        'id': 'saturating_accumulator',
        'title': 'Saturating Accumulator',
        'difficulty': 'Hard',
        'category': 'Datapath',
        'tags': ['accumulator', 'saturating', 'datapath'],
        'module_signature': 'module saturating_accumulator(input clk, input rst, input en, input signed [7:0] d, output reg signed [7:0] q);',
        'statement': 'Implement an 8-bit accumulator that adds an 8-bit input to its stored value when enable is high and saturates at maximum/minimum values on overflow. It must update on the rising edge of clk and support synchronous reset. This block demonstrates arithmetic accumulation with overflow handling in a datapath.',
        'behavior': ['On clk rising edge, if en is 1 add d to q and saturate on overflow.', 'If en is 0, q retains its value.', 'rst synchronously clears q to 0.'],
        'constraints': 'Do not use asynchronous reset or latches.',
        'example': 'clk rst en d | q\n0 1 0 xx | 00000000\n1 0 1 01111111 | 01111111\n1 0 1 00000001 | 01111111',
        'hint': 'Detect signed overflow when adding q and d.'
    },
    {
        'id': 'arithmetic_shift_unit',
        'title': 'Arithmetic Shift Unit',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['shifter', 'signed', 'datapath'],
        'module_signature': 'module arithmetic_shift_unit(input signed [15:0] a, input [3:0] shamt, output [15:0] y);',
        'statement': 'Design an arithmetic right shift unit that shifts a signed 16-bit input right by a 4-bit shift amount while preserving the sign bit. The vacant MSBs should be filled with the original sign. This block is used in signed division and normalization operations.',
        'behavior': ['y is a shifted right version of a with sign extension.', 'If shamt is 0, y equals a.', 'The implementation must be combinational.'],
        'constraints': 'Do not use sequential or clocked behavior.',
        'example': 'a shamt | y\n10000000_00000000 0001 | 11000000_00000000\n01111111_11111111 0010 | 00011111_11111111',
        'hint': 'Shift the vector and fill upper bits with the sign bit.'
    },
    {
        'id': 'flag_generator',
        'title': 'Flag Generator',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['flags', 'status', 'datapath'],
        'module_signature': 'module flag_generator(input [7:0] result, input carry_in, output zero, output negative, output parity, output carry_out);',
        'statement': 'Create a flag generator that computes zero, negative, parity, and carry flags from an 8-bit arithmetic result and carry-in signal. The module should produce outputs suitable for a processor status register. The logic must be combinational.',
        'behavior': ['zero is 1 when result == 0.', 'negative reflects result[7].', 'parity is 1 when result contains an even number of ones.', 'carry_out mirrors carry_in for this block.'],
        'constraints': 'Do not use sequential constructs.',
        'example': 'result carry_in | zero negative parity carry_out\n00000000 0 | 1 0 1 0',
        'hint': 'Compute flags from the result bits and carry signal.'
    },
    {
        'id': 'data_router',
        'title': 'Data Router',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['router', 'mux', 'datapath'],
        'module_signature': 'module data_router(input [7:0] a, input [7:0] b, input [7:0] c, input [7:0] d, input [1:0] sel, output [7:0] y);',
        'statement': 'Implement a 4-way data router that selects one of four 8-bit inputs based on a 2-bit select signal. The selected input should appear on the output without any registered delay. This module is a basic datapath element for multiplexed data paths.',
        'behavior': ['y equals the selected input based on sel.', 'The selection is purely combinational.', 'No state or clocking is allowed.'],
        'constraints': 'Avoid sequential multiplexing or registers.',
        'example': 'sel a b c d | y\n00 00000001 00000010 00000100 00001000 | 00000001\n11 00000001 00000010 00000100 00001000 | 00001000',
        'hint': 'Use a single multiway select structure.'
    },
    {
        'id': 'branch_condition_unit',
        'title': 'Branch Condition Unit',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['branch', 'condition', 'datapath'],
        'module_signature': 'module branch_condition_unit(input signed [7:0] value, input branch_neg, output taken);',
        'statement': 'Create a branch condition unit that asserts a taken signal when an 8-bit signed operand is zero or negative and a separate control bit indicates branch-if-negative. The unit supports conditional branching in a datapath. The output must be combinational.',
        'behavior': ['taken is 1 when branch_neg is 1 and value is zero or negative.', 'taken is 0 otherwise.', 'The logic must be combinational.'],
        'constraints': 'Do not use registers or sequential state.',
        'example': 'value branch_neg | taken\n11111111 1 | 1\n00000001 1 | 0',
        'hint': 'Check the sign bit and zero condition only when branch_neg is asserted.'
    },
    {
        'id': 'signed_magnitude_selector',
        'title': 'Signed Magnitude Selector',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['signed', 'selector', 'datapath'],
        'module_signature': 'module signed_magnitude_selector(input signed [7:0] a, input signed [7:0] b, input sel, output reg signed [7:0] y, output reg negative);',
        'statement': 'Design a datapath selector that compares two 8-bit signed operands and outputs the one with larger signed magnitude when a control input is set. It should also output a flag indicating if the selected operand was negative. This shows magnitude-based decision logic in datapaths.',
        'behavior': ['If sel is 0, select the larger signed operand by value.', 'If sel is 1, select the operand with larger absolute magnitude.', 'negative indicates if y is negative.'],
        'constraints': 'Do not infer sequential state; output may be reg for combinational assignment.',
        'example': 'a b sel | y negative\n00000010 11111110 0 | 00000010 0',
        'hint': 'Implement both signed comparison and absolute-value magnitude comparison.'
    },
    {
        'id': 'address_incrementer',
        'title': 'Address Incrementer',
        'difficulty': 'Easy',
        'category': 'Datapath',
        'tags': ['address', 'increment', 'datapath'],
        'module_signature': 'module address_incrementer(input [15:0] addr, input incr, output [15:0] next_addr);',
        'statement': 'Build an address incrementer that adds 1 to a 16-bit address when incr is high, and otherwise passes the address unchanged. This combinational block is used in instruction fetch and memory addressing paths. The result must wrap naturally on overflow.',
        'behavior': ['If incr is 1, next_addr = addr + 1.', 'If incr is 0, next_addr = addr.', 'The module must be combinational.'],
        'constraints': 'Do not use clocks or sequential elements.',
        'example': 'addr incr | next_addr\n0000000000000000 1 | 0000000000000001\n1111111111111111 1 | 0000000000000000',
        'hint': 'Implement the increment conditionally.'
    },
    {
        'id': 'zero_flag_unit',
        'title': 'Zero Flag Unit',
        'difficulty': 'Easy',
        'category': 'Datapath',
        'tags': ['flag', 'zero', 'datapath'],
        'module_signature': 'module zero_flag_unit(input [7:0] value, output zero);',
        'statement': 'Design a zero flag unit that asserts when an 8-bit value is zero. This unit is a datapath status generator used in branch and condition evaluation. The output should be combinational and instantaneous with input changes.',
        'behavior': ['zero is 1 when value == 0.', 'zero is 0 otherwise.', 'No sequential elements may be used.'],
        'constraints': 'Do not use registers or flip-flops.',
        'example': 'value | zero\n00000000 | 1\n00000001 | 0',
        'hint': 'Compare all bits to zero at once.'
    },
    {
        'id': 'shifter_mux',
        'title': 'Shifter Multiplexer',
        'difficulty': 'Medium',
        'category': 'Datapath',
        'tags': ['shifter', 'mux', 'datapath'],
        'module_signature': 'module shifter_mux(input [7:0] a, input [7:0] b, input [1:0] sel, output [7:0] y);',
        'statement': 'Create a multiplexer that selects among four 8-bit shift-related values: the original input, input shifted left by one, input shifted right by one, and bitwise inverse. The selection is controlled by sel. This unit demonstrates a datapath selection stage.',
        'behavior': ['sel=00 outputs a.', 'sel=01 outputs a << 1.', 'sel=10 outputs a >> 1.', 'sel=11 outputs ~a.'],
        'constraints': 'Do not infer sequential state or registers.',
        'example': 'a sel | y\n00000001 01 | 00000010\n00000010 10 | 00000001',
        'hint': 'Use separate combinational expressions for each option.'
    },
    {
        'id': 'find_bug_dff_reset_polarity',
        'title': 'Find the Bug: D Flip-Flop Reset Polarity',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['debugging', 'reset', 'flip-flop'],
        'module_signature': 'module find_bug_dff_reset_polarity(input clk, input rst, input d, output reg q);',
        'statement': 'A broken D flip-flop module is provided that uses the wrong reset polarity and fails to clear on a high reset signal. Your task is to identify the bug and implement the corrected flip-flop with active-high synchronous reset. The module should behave correctly for all clock and reset combinations.',
        'behavior': ['q captures d on the rising edge when rst is low.', 'q clears to 0 on the rising edge when rst is high.', 'The reset is synchronous and active-high.'],
        'constraints': 'Do not use asynchronous reset or implicit level-sensitive constructs.',
        'example': 'clk rst d | q\n0 1 1 | 0\n1 0 1 | 1\n1 1 0 | 0',
        'hint': 'The bug is the wrong reset polarity in the clocked always block.'
    },
    {
        'id': 'write_testbench_full_adder',
        'title': 'Write Testbench for Full Adder',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['testbench', 'verification', 'full-adder'],
        'module_signature': 'module write_testbench_full_adder; // testbench only',
        'statement': 'Write a testbench for a given full adder module. The testbench should instantiate the full adder, apply all input combinations, and verify the sum and carry outputs. The expected waveform or prints should be checked automatically in simulation.',
        'behavior': ['Instantiate the provided full adder module.', 'Apply all eight combinations of inputs a, b, and cin.', 'Compare outputs to expected sum and cout values.'],
        'constraints': 'Do not modify the full adder DUT; the testbench should remain separate.',
        'example': 'a b cin | sum cout\n0 0 0 | 0 0\n1 1 1 | 1 1',
        'hint': 'Use $display and a loop to verify all input combinations.'
    },
    {
        'id': 'identify_race_condition',
        'title': 'Identify the Race Condition',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['race', 'debugging', 'sequential'],
        'module_signature': 'module identify_race_condition(input clk, input rst, input a, input b, output reg [1:0] q);',
        'statement': 'A sequential module shows intermittent behavior because two signals are assigned in parallel when they should be ordered. Your task is to identify the race condition in the design and rewrite the logic so the updates occur in a deterministic clocked manner. The corrected circuit should behave consistently under all clock cycles.',
        'behavior': ['q updates on the clock edge without hazards from parallel combinational assignments.', 'rst synchronously clears q to 0.', 'The corrected design must avoid race conditions between q bits.'],
        'constraints': 'Do not use nested nonblocking/blocking mix-ups that create races.',
        'example': 'clk rst a b | q\n1 0 1 0 | 01\n1 0 0 1 | 10',
        'hint': 'Use nonblocking assignments consistently in the clocked block.'
    },
    {
        'id': 'assertion_checker',
        'title': 'Assertion Checker',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['assertion', 'monitor', 'verification'],
        'module_signature': 'module assertion_checker(input [3:0] value, output reg fault);',
        'statement': 'Create a combinational property checker that asserts when a 4-bit value is out of a safe range and holds a fault flag. The module should output an alert signal when the value exceeds 12. This helps verify safety conditions in a datapath.',
        'behavior': ['fault is 1 when value > 12.', 'fault is 0 otherwise.', 'The checker is combinational in behavior.'],
        'constraints': 'Do not use sequential storage for the quality check.',
        'example': 'value | fault\n1100 | 0\n1101 | 1',
        'hint': 'Implement the condition with simple comparison logic.'
    },
    {
        'id': 'testbench_for_mux',
        'title': 'Write Testbench for Multiplexer',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['testbench', 'verification', 'mux'],
        'module_signature': 'module testbench_for_mux; // testbench only',
        'statement': 'Write a testbench for a 2:1 multiplexer module. The testbench should apply all combinations of the two inputs and select line, then print the selected output. The design should confirm the multiplexer behaves correctly for every vector.',
        'behavior': ['Instantiate the mux DUT.', 'Apply all four combinations of inputs with sel = 0 and sel = 1.', 'Check that output matches the selected input.'],
        'constraints': 'Do not alter the DUT interface in the testbench.',
        'example': 'a b sel | y\n0 0 0 | 0\n1 1 1 | 1',
        'hint': 'Use sequential stimulus generation in the initial block.'
    },
    {
        'id': 'find_bug_clock_divider',
        'title': 'Find the Bug: Clock Divider',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['debugging', 'clock', 'sequential'],
        'module_signature': 'module find_bug_clock_divider(input clk, input rst, input [3:0] n, output reg clk_out);',
        'statement': 'A clock divider module is provided with a bug that causes an incorrect duty cycle. Your task is to fix the design so the output clock toggles every N input cycles and has a 50% duty cycle when N is even. The corrected module should use synchronous counters.',
        'behavior': ['clk_out toggles every n input cycles.', 'clk_out should be low after reset until enough cycles accumulate.', 'rst synchronously resets the divider.'],
        'constraints': 'Do not use asynchronous feedback or combinational loops.',
        'example': 'n clk_out\n0001 0 1 0 1\n0010 0 0 1 1',
        'hint': 'Count input cycles and toggle the output using a registered counter.'
    },
    {
        'id': 'verify_fifo_full_empty',
        'title': 'Verify FIFO Full/Empty',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['fifo', 'testbench', 'memory'],
        'module_signature': 'module verify_fifo_full_empty; // testbench only',
        'statement': 'Design a testbench that verifies an 8-entry FIFO sets full and empty flags correctly and preserves data order. The testbench should perform writes until full, then reads until empty, checking the output stream. It must catch misbehavior in both boundary conditions.',
        'behavior': ['Check that full goes high when the FIFO is full.', 'Check that empty goes high when the FIFO is empty.', 'Verify data comes out in the same order it went in.'],
        'constraints': 'Do not rely on unspecified timing; use clocked stimulus.',
        'example': 'push pop | data out\n1 0 | A B C...\n0 1 | A B C...',
        'hint': 'Use a deterministic sequence of writes and reads in your testbench.'
    },
    {
        'id': 'find_bug_priority_encoder',
        'title': 'Find the Bug: Priority Encoder',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['debugging', 'priority', 'combinational'],
        'module_signature': 'module find_bug_priority_encoder(input [7:0] in, output reg [2:0] code, output reg valid);',
        'statement': 'A priority encoder module fails when multiple inputs are asserted simultaneously. Your task is to identify the bug in the priority logic and fix the encoder so it always reports the highest-priority asserted bit. The corrected module should also assert valid only when at least one input is high.',
        'behavior': ['code indicates the highest-priority asserted bit.', 'valid is 1 when any input is high.', 'ties are resolved by highest input index.'],
        'constraints': 'Do not use sequential or registered state other than combinational outputs.',
        'example': 'in | valid code\n00010010 | 1 100\n11000000 | 1 111',
        'hint': 'Examine the input bits from highest priority to lowest.'
    },
    {
        'id': 'testbench_for_sign_extender',
        'title': 'Write Testbench for Sign Extender',
        'difficulty': 'Easy',
        'category': 'Verification',
        'tags': ['testbench', 'sign-extension', 'verification'],
        'module_signature': 'module testbench_for_sign_extender; // testbench only',
        'statement': 'Write a testbench that exercises a sign extender with positive and negative inputs. The testbench should confirm the extended bits replicate the sign bit correctly. It should print the input and output values for verification.',
        'behavior': ['Instantiate the sign extender DUT.', 'Apply examples with positive and negative 8-bit values.', 'Verify the upper bits match the sign bit.'],
        'constraints': 'Do not modify the DUT interface.',
        'example': 'a        | y\n10000000 | 11111111_10000000\n01111111 | 00000000_01111111',
        'hint': 'Use both negative and nonnegative examples in the testbench.'
    },
    {
        'id': 'formal_property_checker',
        'title': 'Formal Property Checker',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['assertion', 'formal', 'verification'],
        'module_signature': 'module formal_property_checker(input [7:0] value, input permit, output reg violation);',
        'statement': 'Create an assertion-like module that flags when an 8-bit input violates a safety property: the value must never exceed 200 when a permit signal is low. The output should be 1 only when the violation occurs. This mimics simple formal verification properties in hardware checking.',
        'behavior': ['violation is 1 when permit is 0 and value > 200.', 'violation is 0 otherwise.', 'The module behavior is combinational.'],
        'constraints': 'Do not use sequential state or clocks.',
        'example': 'permit value | violation\n0 11001001 | 1\n1 11001001 | 0',
        'hint': 'Use a single condition that captures both permit and threshold.'
    },
    {
        'id': 'buggy_register_debug',
        'title': 'Debug the Buggy Register',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['debugging', 'register', 'sequential'],
        'module_signature': 'module buggy_register_debug(input clk, input rst, input en, input [7:0] d, output reg [7:0] q);',
        'statement': 'A register module is behaving incorrectly because it loads data when the enable signal is deasserted. Your task is to fix the logic so the register only updates on enable high at the clock edge. The register should also support synchronous reset.',
        'behavior': ['q captures d only when en is 1 at the rising edge.', 'If en is 0, q holds its current value.', 'rst synchronously clears q.'],
        'constraints': 'Do not use latches or asynchronous set/reset behavior.',
        'example': 'clk rst en d | q\n1 0 1 10101010 | 10101010\n1 0 0 01010101 | 10101010',
        'hint': 'Use an if statement inside the clocked always block to gate updates.'
    },
    {
        'id': 'testbench_for_branch_unit',
        'title': 'Write Testbench for Branch Unit',
        'difficulty': 'Medium',
        'category': 'Verification',
        'tags': ['testbench', 'branch', 'verification'],
        'module_signature': 'module testbench_for_branch_unit; // testbench only',
        'statement': 'Write a testbench for a branch condition unit that checks negative and zero flags. The testbench should apply representative values and verify the taken output. It should help catch logic errors in branch evaluation.',
        'behavior': ['Instantiate the branch condition DUT.', 'Apply signed values around zero and negative boundaries.', 'Verify taken matches the expected branch decision.'],
        'constraints': 'Do not alter the DUT module in the testbench.',
        'example': 'value branch_neg | taken\n11111111 1 | 1\n00000001 1 | 0',
        'hint': 'Cover both zero, negative, and positive cases.'
    },
    {
        'id': 'find_bug_memory_arbitration',
        'title': 'Find the Bug: Memory Arbitration',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['debugging', 'memory', 'arbiter'],
        'module_signature': 'module find_bug_memory_arbitration(input clk, input rst, input [2:0] req, output reg [2:0] grant);',
        'statement': 'A memory arbiter is granting the wrong requester when two requests arrive at once. Your task is to correct the arbitration logic so the highest-priority requester wins and grants remain stable until release. The corrected arbiter must also deassert all grants when no requests are active.',
        'behavior': ['One grant at most may be asserted at a time.', 'Highest-priority request wins when multiple requests are active.', 'rst synchronously clears all grants.'],
        'constraints': 'Avoid asynchronous or combinational grant chasing.',
        'example': 'req grant\n110 100\n010 010',
        'hint': 'Use a registered grant state and update it each clock cycle.'
    },
    {
        'id': 'verify_register_file_read_ports',
        'title': 'Verify Register File Read Ports',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['register-file', 'verification', 'read-port'],
        'module_signature': 'module verify_register_file_read_ports; // testbench only',
        'statement': 'Write a testbench that verifies a register file with two read ports returns correct values on both outputs. The testbench should write known values to multiple addresses and compare the read ports for both matching and different addresses. It should also verify proper behavior after reset.',
        'behavior': ['Write values to multiple registers.', 'Verify read_data_a and read_data_b return the correct values.', 'Check behavior for same-address and different-address reads.'],
        'constraints': 'Do not modify the DUT under test.',
        'example': 'write_addr read_addr_a read_addr_b | read_data_a read_data_b\n010 010 011 | val val2',
        'hint': 'Use separate read addresses to verify independent read port behavior.'
    },
    {
        'id': 'testbench_for_sram',
        'title': 'Write Testbench for SRAM',
        'difficulty': 'Hard',
        'category': 'Verification',
        'tags': ['testbench', 'sram', 'verification'],
        'module_signature': 'module testbench_for_sram; // testbench only',
        'statement': 'Develop a testbench for an SRAM behavioral model that performs write and read operations to multiple addresses. The testbench should check that written values are returned correctly after writes and that memory persists across cycles. The design should also verify reset behavior.',
        'behavior': ['Write values to a sequence of addresses.', 'Read them back later and compare to expected values.', 'Verify that reset invalidates or clears memory if specified.'],
        'constraints': 'Do not alter the SRAM DUT interface.',
        'example': 'addr wr_en din | dout\n0000 1 10101010 | 10101010\n0000 0 xx | 10101010',
        'hint': 'Use a clocked sequence to exercise writes and reads.'
    },
    {
        'id': 'modulo_unit',
        'title': 'Modulo Arithmetic Unit',
        'difficulty': 'Medium',
        'category': 'Arithmetic',
        'tags': ['modulo', 'arithmetic', 'datapath'],
        'module_signature': 'module modulo_unit(input [7:0] a, input [7:0] b, output reg [7:0] remainder);',
        'statement': 'Implement a combinational unit that computes the remainder of unsigned division a % b for 8-bit operands. If b is zero, the module should output zero. This is a datapath block for remainder arithmetic.',
        'behavior': ['remainder = a % b when b != 0.', 'remainder = 0 when b == 0.', 'The unit must be purely combinational.'],
        'constraints': 'Do not use sequential division algorithms or loops with hidden state.',
        'example': 'a b | remainder\n00001010 00000011 | 00000001\n00001111 00000100 | 00000011',
        'hint': 'Implement the remainder using combinational subtraction and comparison logic if needed.'
    },
    {
        'id': 'population_count',
        'title': 'Population Count',
        'difficulty': 'Medium',
        'category': 'Combinational',
        'tags': ['popcount', 'bit-count', 'combinational'],
        'module_signature': 'module population_count(input [7:0] a, output reg [3:0] count);',
        'statement': 'Create a combinational unit that counts the number of 1 bits in an 8-bit input and outputs the count. This is useful for Hamming weight calculations and error checking circuits.',
        'behavior': ['count is the number of ones in a.', 'The output must be correct for any 8-bit input.', 'No sequential or register-based counting is allowed.'],
        'constraints': 'Do not use sequential loops or memory-based counters.',
        'example': 'a        | count\n00000000 | 0000\n11110000 | 0100\n10101010 | 0100',
        'hint': 'Use a tree of bitwise adders or reduction logic.'
    },
    {
        'id': 'bit_reversal',
        'title': 'Bit Reversal',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['bit-manipulation', 'combinational', 'datapath'],
        'module_signature': 'module bit_reversal(input [7:0] a, output [7:0] y);',
        'statement': 'Implement an 8-bit bit reversal module that outputs the input bits in reverse order. The least significant input bit should become the most significant output bit. This is commonly used in signal processing algorithms.',
        'behavior': ['y is the bitwise reverse of a.', 'The module must be purely combinational.', 'No sequential storage is allowed.'],
        'constraints': 'Do not use loops or registers to perform the reversal.',
        'example': 'a        | y\n00000001 | 10000000\n10101010 | 01010101',
        'hint': 'Map each input bit to its reversed output position explicitly.'
    },
    {
        'id': 'saturating_counter',
        'title': 'Saturating Counter',
        'difficulty': 'Medium',
        'category': 'Sequential',
        'tags': ['counter', 'saturating', 'sequential'],
        'module_signature': 'module saturating_counter(input clk, input rst, input en, output reg [3:0] count);',
        'statement': 'Design a 4-bit saturating counter that increments on each clock edge when enabled, but stops at 15 instead of wrapping. A synchronous reset should return the count to zero. This is useful in control systems where overflow must be prevented.',
        'behavior': ['If en is 1, count increments until 15 and then holds.', 'If en is 0, count remains unchanged.', 'rst synchronously clears count to 0.'],
        'constraints': 'Do not allow the count to wrap around after reaching 15.',
        'example': 'count en | count_next\n1110 1 | 1111\n1111 1 | 1111',
        'hint': 'Check the current value before incrementing and hold at the limit.'
    },
    {
        'id': 'priority_encoder_4to2',
        'title': '4-to-2 Priority Encoder',
        'difficulty': 'Easy',
        'category': 'Combinational',
        'tags': ['encoder', 'priority', 'combinational'],
        'module_signature': 'module priority_encoder_4to2(input [3:0] in, output reg [1:0] code, output reg valid);',
        'statement': 'Implement a 4-to-2 priority encoder that outputs the binary index of the highest-priority set input. If no input is asserted, valid should be low and code should be zero. Priority is assigned from input 3 down to input 0.',
        'behavior': ['code reports the highest asserted bit position when any input is set.', 'valid is 1 when any bit is asserted, else 0.', 'The module must be purely combinational.'],
        'constraints': 'Do not use registers beyond combinational output assignments.',
        'example': 'in   | valid code\n0000 | 0 00\n0101 | 1 10\n1000 | 1 11',
        'hint': 'Evaluate inputs from highest to lowest priority.'
    }
]

assert len(problems_data) == 100, f'expected 100 problems, got {len(problems_data)}'
print(json.dumps(problems_data, indent=2))
