import json

bases = [
    ('mux_2to1', '2:1 Multiplexer', 'Easy', 'Combinational', ['mux', 'selector', 'combinational'],
     'Implement a 2:1 multiplexer that selects between two 8-bit inputs based on a single select line. The module must drive the output combinationally with no registers or clocks. The select signal must be stable during evaluation, and invalid timing should not be assumed. This circuit is a classic data-path selector used in ALU and routing logic.',
     'module mux_2to1(input [7:0] a, input [7:0] b, input sel, output [7:0] y);',
     ['If sel is 0, y must equal a; if sel is 1, y must equal b.', 'No sequential elements; behavior must be purely combinational.', 'All bits of y must update immediately after inputs change.'],
     'Do not use any clocks or sequential constructs.',
     'a b sel | y\n00000000 11111111 0 | 00000000\n00000000 11111111 1 | 11111111\n10101010 01010101 1 | 01010101',
     'Use a single conditional assignment or bitwise mask.'),
    ('decoder_3to8', '3-to-8 Decoder', 'Easy', 'Combinational', ['decoder', 'one-hot', 'combinational'],
     'Design a 3-to-8 decoder that converts a 3-bit binary input into an eight-bit one-hot output. Only one output line may be asserted at a time while all others remain low. If the input is out of range, all outputs should remain zero. This module is often used in address decoding and instruction dispatch logic.',
     'module decoder_3to8(input [2:0] sel, output [7:0] y);',
     ['One-hot output: y[i] = 1 when sel equals i, else 0.', 'All outputs must be driven combinationally.', 'No use of memories, latches, or sequential blocks.'],
     'Do not use a behavioral for-loop for the decoder.',
     'sel | y\n000 | 00000001\n010 | 00000100\n111 | 10000000',
     'Think of the decoder as a binary-to-one-hot converter.'),
    ('priority_encoder_8to3', '8-to-3 Priority Encoder', 'Medium', 'Combinational', ['priority', 'encoder', 'combinational'],
     'Create an 8-to-3 priority encoder that encodes the highest-priority asserted input into a binary output. Input 7 has the highest priority and input 0 the lowest. If no inputs are asserted, output should be zero and valid must be low. The encoder must resolve priority with a single combinational pass.',
     'module priority_encoder_8to3(input [7:0] in, output reg [2:0] code, output valid);',
     ['code indicates the index of the highest asserted input.', 'valid is 1 when any input bit is high, else 0.', 'Behavior must be purely combinational despite reg output syntax.'],
     'Do not use sequential procedural loops or clocked always blocks.',
     'in       | valid code\n00000000 | 0 000\n00010010 | 1 100\n10000001 | 1 111',
     'Evaluate inputs from highest to lowest priority.'),
    ('comparator_unsigned', 'Unsigned Comparator', 'Easy', 'Combinational', ['comparator', 'comparison', 'combinational'],
     'Build an unsigned comparator that compares two 8-bit operands and reports greater-than, equal, and less-than conditions. The outputs must reflect the result of the comparison for every change of the inputs. This module is pure combinational logic and must not infer any storage elements.',
     'module comparator_unsigned(input [7:0] a, input [7:0] b, output gt, output eq, output lt);',
     ['gt is 1 when a > b.', 'eq is 1 when a == b.', 'lt is 1 when a < b.'],
     'Do not use sequential constructs or case statements with hidden registers.',
     'a b | gt eq lt\n00000001 00000010 | 0 0 1\n00000011 00000011 | 0 1 0\n11111111 00000000 | 1 0 0',
     'You can derive lt from gt and eq if you like.'),
    ('even_parity_generator', 'Even Parity Generator', 'Easy', 'Combinational', ['parity', 'reduction', 'combinational'],
     'Implement an even parity generator for an 8-bit input. The output should be high when the input contains an even number of ones. The module must be stable for all input vectors and suitable for parity checking in simple link-layer circuits.',
     'module even_parity_generator(input [7:0] a, output parity);',
     ['parity is 1 when the number of 1 bits in a is even.', 'parity is 0 when the number of 1 bits is odd.', 'No sequential or clocked logic may be used.'],
     'Do not use built-in reduction XOR directly if you want a structural solution.',
     'a        | parity\n00000000 | 1\n00000001 | 0\n10101010 | 1',
     'Treat parity as a multi-input XOR reduction with inverted output.'),
    ('sign_extender_8to16', 'Sign Extender', 'Easy', 'Combinational', ['sign-extender', 'datapath', 'combinational'],
     'Design an 8-bit sign extender that converts a signed 8-bit input into a 16-bit two’s complement output. The top 8 bits of the result must be copies of the input sign bit. The module is used in datapath code to widen signed values before arithmetic.',
     'module sign_extender(input [7:0] a, output [15:0] y);',
     ['y[7:0] must equal a.', 'y[15:8] must be all 1s when a[7] is 1 and all 0s when a[7] is 0.', 'Only combinational logic is allowed.'],
     'Do not use sequential constructs or memory elements.',
     'a        | y\n10000000 | 11111111_10000000\n01111111 | 00000000_01111111',
     'Copy the sign bit across the upper bits.'),
    ('zero_detector', 'Zero Detector', 'Easy', 'Combinational', ['comparator', 'detector', 'combinational'],
     'Create an 8-bit zero detector that asserts output when all bits of the input are zero. The circuit should return zero otherwise. It is a simple combinational check used in branch condition generation and comparator datapaths.',
     'module zero_detector(input [7:0] a, output is_zero);',
     ['is_zero is 1 when a == 0.', 'is_zero is 0 for any nonzero input.', 'Do not infer registers or sequential logic.'],
     'Do not use a sequential loop or latch inference.',
     'a        | is_zero\n00000000 | 1\n00000001 | 0\n11111111 | 0',
     'All bits must be compared to zero in a single combinational expression.'),
    ('one_hot_to_binary', 'One-Hot to Binary Encoder', 'Medium', 'Combinational', ['encoder', 'one-hot', 'combinational'],
     'Design a one-hot to binary encoder that converts an eight-bit one-hot input into a 3-bit binary output plus a valid signal. If the input is not one-hot or is all zeros, valid must be 0 and code must be 0. This module is useful in priority schemes and state decoders.',
     'module one_hot_to_binary(input [7:0] one_hot, output reg [2:0] code, output valid);',
     ['code reports the position of the asserted bit if exactly one input is high.', 'valid is 1 only if exactly one input bit is high.', 'If zero or multiple bits are asserted, valid is 0 and code is 0.'],
     'Do not use sequential pipelines or internal state.',
     'one_hot | valid code\n00000000 | 0 000\n00010000 | 1 100\n11000000 | 0 000',
     'Count the asserted signals and encode only when the count is one.'),
    ('majority_gate', '3-Input Majority Gate', 'Easy', 'Combinational', ['majority', 'voting', 'combinational'],
     'Build a 3-input majority gate that outputs 1 when at least two of the three inputs are 1. The output must be low for one or zero asserted inputs. It is a basic voting circuit used in fault-tolerant systems and combinational logic designs.',
     'module majority_gate(input a, input b, input c, output y);',
     ['y is 1 when two or three inputs are 1.', 'y is 0 when zero or one inputs are 1.', 'The design must be pure combinational logic.'],
     'Avoid sequential constructs and latches.',
     'a b c | y\n0 0 0 | 0\n1 1 0 | 1\n1 1 1 | 1',
     'Compute the sum of the bits and compare to two.'),
    ('detect_msb_one', 'MSB One Detector', 'Easy', 'Combinational', ['detector', 'combinational', 'bit-scan'],
     'Design an 8-bit detector that asserts output when the most significant bit of the input is 1. The circuit should ignore lower bits and react combinationally to input changes. This is useful for sign detection and branch decisions in unsigned comparisons.',
     'module detect_msb_one(input [7:0] a, output msb_one);',
     ['msb_one is 1 when a[7] is 1.', 'msb_one is 0 otherwise.', 'No sequential or clocked logic is permitted.'],
     'Do not use any registers or case-statements that infer state.',
     'a        | msb_one\n10000000 | 1\n01111111 | 0',
     'Only the top bit determines the output.'),
    ('carry_generate_combiner', 'Carry Generate Combiner', 'Medium', 'Combinational', ['carry', 'adder', 'combinational'],
     'Implement an 8-bit carry generate and propagate unit that produces group generate and group propagate signals for a ripple-carry adder stage. The outputs should describe whether this block will generate a carry regardless of input carry, or propagate an input carry to the next stage. This combinational module is a datapath building block used in faster adder designs.',
     'module carry_generate_combiner(input [7:0] a, input [7:0] b, output g, output p);',
     ['g is 1 when a+b will generate a carry within the block regardless of carry-in.', 'p is 1 when the block propagates a carry-in to carry-out.', 'The design must be purely combinational.'],
     'Do not instantiate a full adder array with registers.',
     'a b | g p\n00000000 00000001 | 0 0\n11111111 00000001 | 1 0\n01010101 10101010 | 0 1',
     'Use bitwise and/or reduction logic to capture generate and propagate behavior.'),
    ('min_max_selector', 'Min/Max Selector', 'Medium', 'Combinational', ['selector', 'comparator', 'datapath'],
     'Create a combinational min/max selector that chooses either the smaller or larger of two 8-bit signed inputs based on a control input. When sel is 0, output the minimum; when sel is 1, output the maximum. The module should handle two’s complement operands correctly and produce valid signed results.',
     'module min_max_selector(input signed [7:0] a, input signed [7:0] b, input sel, output signed [7:0] y);',
     ['When sel is 0, y equals the smaller signed operand.', 'When sel is 1, y equals the larger signed operand.', 'Equal operands may output either value.'],
     'Do not use sequential logic or registers.',
     'a b sel | y\n00000001 00000010 0 | 00000001\n11111111 00000001 1 | 00000001',
     'Compare operands as signed numbers, not unsigned.'),
    ('threshold_detector', 'Threshold Detector', 'Easy', 'Combinational', ['threshold', 'comparator', 'combinational'],
     'Build an 8-bit threshold detector that asserts output when the input exceeds a fixed constant value of 100 decimal. The output must be high for 101 and greater, and low for 100 and below. This is a common operation in analog-to-digital and control circuits.',
     'module threshold_detector(input [7:0] a, output above_threshold);',
     ['above_threshold is 1 when a > 100.', 'above_threshold is 0 when a <= 100.', 'The logic must be purely combinational.'],
     'Do not use a sequential comparator or state machine.',
     'a      | above_threshold\n01100100 | 0\n01100101 | 1\n10000000 | 1',
     'Hardcode the threshold comparison with bitwise logic if needed.'),
    ('absolute_value_unit', 'Absolute Value Unit', 'Medium', 'Combinational', ['absolute', 'signed', 'datapath'],
     'Design an absolute value unit that converts a signed 8-bit input to its nonnegative magnitude. The output should be the input when nonnegative and the two’s complement negation when negative. This module is used in datapath units requiring magnitude comparisons.',
     'module absolute_value_unit(input signed [7:0] a, output reg [7:0] y);',
     ['y is equal to a when a is nonnegative.', 'y is equal to -a when a is negative.', 'The design must be combinational.'],
     'Do not infer sequential storage or clocks.',
     'a | y\n00000011 | 00000011\n11111101 | 00000011',
     'Select between a and its negation based on the sign bit.'),
    ('bitwise_nand', 'Bitwise NAND', 'Easy', 'Combinational', ['nand', 'bitwise', 'combinational'],
     'Create an 8-bit bitwise NAND operator. The output should be the bitwise NAND of the two 8-bit inputs. This module is useful for building logic functions and implementing complex logic gates.',
     'module bitwise_nand(input [7:0] a, input [7:0] b, output [7:0] y);',
     ['y is the bitwise NAND of a and b.', 'The result is 1 for each bit pair that is not both 1.', 'The design must be combinational.'],
     'Do not use registers or sequential constructs.',
     'a b | y\n11110000 10101010 | 01010101',
     'Use bitwise operators directly for the NAND operation.'),
]

# Sequential extras to reach 14 if needed
bases += [
    ('bit_pulse_generator', 'Bit Pulse Generator', 'Medium', 'Sequential', ['pulse', 'sequential', 'register'],
     'Implement a one-shot pulse generator that produces a single-cycle pulse whenever an input bit transitions from 0 to 1. The output must remain low otherwise and reset synchronously. This is useful for edge-triggered event capture in sequential logic.',
     'module bit_pulse_generator(input clk, input rst, input in_bit, output reg pulse);',
     ['pulse is 1 for exactly one cycle after a rising transition.', 'pulse is 0 for all other cycles.', 'rst synchronously clears pulse to 0.'],
     'Do not use asynchronous edge detection or latches.',
     'in_bit | pulse\n0 0 1 | 1\n1 1 0 | 0',
     'Store the previous sampled value and compare it to the current value.'),
    ('synchronous_clear_counter', 'Synchronous Clear Counter', 'Easy', 'Sequential', ['counter', 'reset', 'sequential'],
     'Design a 4-bit counter with synchronous clear that counts upward on each clock edge. When clear is asserted, the counter should reset to zero on the next clock. The counter must wrap around after 15 to 0.',
     'module synchronous_clear_counter(input clk, input rst, input clear, output reg [3:0] count);',
     ['count increments by 1 each clock cycle when clear is 0.', 'If clear is 1 on a rising edge, count becomes 0.', 'rst synchronously resets count to 0.'],
     'Do not use asynchronous resets or latches.',
     'clk rst clear | count\n1 0 0 | 0001\n1 1 0 | 0000',
     'Clock the counter and prioritize reset logic correctly.'),
]

# FSM extras to reach 14
bases += [
    ('oven_controller', 'Oven Controller FSM', 'Hard', 'FSM', ['fsm', 'thermostat', 'controller'],
     'Build an oven controller FSM with preheat, cook, and cooldown states. It should transition on start and stop commands and maintain a safe cooldown period after cooking. A synchronous reset should return it to the idle state.',
     'module oven_controller(input clk, input rst, input start, input stop, output reg preheat, output reg cook, output reg cooldown);',
     ['Only one state output may be high at a time.', 'start moves the FSM from idle to preheat, then cook.', 'stop begins cooldown before returning to idle.'],
     'Do not use asynchronous state changes or latches.',
     'start stop | preheat cook cooldown\n1 0 | 1 0 0\n0 1 | 0 0 1',
     'Use named states and transition logic.'),
    ('door_lock_controller', 'Door Lock Controller', 'Medium', 'FSM', ['fsm', 'security', 'controller'],
     'Design a door lock FSM that unlocks when the correct 4-bit code is entered and then relocks after one pass of the handle. The module should support sequential code entry and reject incorrect sequences. A synchronous reset should force the lock to the locked state.',
     'module door_lock_controller(input clk, input rst, input [3:0] code_in, input enter, output reg locked);',
     ['locked is 0 when the correct code has been entered and the handle has passed.', 'locked is 1 initially and after incorrect code sequences.', 'rst synchronously locks the door.'],
     'Do not use combinational state inference.',
     'code_in enter | locked\n0101 1 | 0\n1111 1 | 1',
     'Track the expected code digits through FSM states.'),
]

# Arithmetic extras to reach 14
bases += [
    ('saturating_subtractor', 'Saturating Subtractor', 'Medium', 'Arithmetic', ['subtractor', 'saturating', 'arithmetic'],
     'Implement an 8-bit saturating subtractor that clamps the signed result at -128 or +127 on overflow. The subtractor should compute a - b and saturate the result when the signed difference exceeds representable bounds. This prevents wraparound in arithmetic datapaths.',
     'module saturating_subtractor(input signed [7:0] a, input signed [7:0] b, output reg signed [7:0] y);',
     ['y = a - b unless signed overflow occurs.', 'Positive overflow saturates to 127.', 'Negative overflow saturates to -128.'],
     'Do not use behavioral constructs that ignore signed overflow semantics.',
     'a b | y\n01111111 11111111 | 01111111\n10000000 00000001 | 10000000',
     'Detect signed overflow by comparing operand signs and result signs.'),
    ('multiplier_accumulator', 'Multiplier Accumulator', 'Hard', 'Arithmetic', ['multiplier', 'accumulator', 'arithmetic'],
     'Build a 4-bit multiplier-accumulator that multiplies two 4-bit unsigned operands and adds the result to an 8-bit accumulator. The accumulator must update on a clock edge and support synchronous reset. This unit is common in DSP datapaths.',
     'module multiplier_accumulator(input clk, input rst, input en, input [3:0] a, input [3:0] b, output reg [7:0] acc);',
     ['When en is 1, acc <= acc + (a * b) on the rising edge.', 'If en is 0, acc retains its value.', 'rst synchronously clears acc to 0.'],
     'Do not use asynchronous reset or combinational accumulation.',
     'clk rst en a b | acc\n0 1 0 xx | 00000000\n1 0 1 0011 0010 | 00000110',
     'Use a register for acc and compute the product combinationally.'),
]

# Memory extras to reach 14
bases += [
    ('banked_register_file', 'Banked Register File', 'Hard', 'Memory', ['register-file', 'banked', 'memory'],
     'Implement a banked register file with two 8-entry banks and one write port. The bank select signal chooses which bank receives writes. Reads should return values from both banks simultaneously on separate outputs.',
     'module banked_register_file(input clk, input rst, input write_en, input bank_sel, input [2:0] write_addr, input [7:0] write_data, input [2:0] read_addr_a, input [2:0] read_addr_b, output [7:0] read_data_a, output [7:0] read_data_b);',
     ['write_data is stored in the selected bank when write_en is 1.', 'read_data_a and read_data_b reflect their respective bank values.', 'rst synchronously clears both banks.'],
     'Do not use vendor-specific multi-bank memory macros.',
     'bank_sel write_en write_addr | read_data_a\n0 1 010 | data',
     'Model each bank as an independent register array.'),
    ('pointer_based_buffer', 'Pointer-Based Buffer', 'Medium', 'Memory', ['buffer', 'pointer', 'memory'],
     'Design a 4-entry buffer with separate write and read pointers and full/empty indicators. Writes advance the write pointer and reads advance the read pointer on the clock. The buffer must be circular and handle simultaneous write/read correctly.',
     'module pointer_based_buffer(input clk, input rst, input write_en, input read_en, input [7:0] din, output reg [7:0] dout, output reg full, output reg empty);',
     ['write_en stores din when full is 0.', 'read_en outputs the next value when empty is 0.', 'full/empty flags indicate buffer status.'],
     'Do not use external queue primitives.',
     'write_en read_en | full empty dout\n1 0 | 0 0 xx\n0 1 | 0 0 stored',
     'Maintain write/read pointers and count entries.'),
]

# Datapath extras to reach 15
bases += [
    ('barrel_shifter_rotate', 'Barrel Shifter with Rotate', 'Medium', 'Datapath', ['shifter', 'rotate', 'datapath'],
     'Add a rotate-right operation to the existing barrel shifter concept. The module should optionally rotate the 32-bit input right by the shift amount while preserving all bits. This exercise extends a datapath shifter with rotation functionality.',
     'module barrel_shifter_rotate(input [31:0] a, input [4:0] shamt, input rotate, output [31:0] y);',
     ['If rotate is 0, perform logical right shift.', 'If rotate is 1, perform rotate right.', 'The design must be combinational.'],
     'Do not infer sequential state or registers.',
     'a shamt rotate | y\n000...1 00001 1 | 100...0',
     'Use carry-around wiring for rotate right.'),
]

# Verification extras to reach 15
bases += [
    ('testbench_for_priority_encoder', 'Write Testbench for Priority Encoder', 'Medium', 'Verification', ['testbench', 'priority', 'verification'],
     'Write a testbench that exercises a priority encoder with multiple simultaneous input assertions. The testbench should verify that the highest priority input is encoded and that valid is asserted only when at least one input is high. Print the outputs for each stimulus vector.',
     'module testbench_for_priority_encoder; // testbench only',
     ['Instantiate the priority encoder DUT.', 'Apply vectors with one-hot and multi-hot inputs.', 'Check code and valid outputs against the expected highest-priority behavior.'],
     'Do not modify the DUT module under test.',
     'inputs | valid code\n10010000 | 1 111\n00000000 | 0 000',
     'Include multi-input cases to ensure correct priority handling.'),
]

# Ensure total count is 100
assert len(bases) == 100, f'expected 100 problems, got {len(bases)}'

for pid, title, difficulty, category, tags, statement, sig, behavior, constraints, example, hint in bases:
    problems.append({
        'id': pid,
        'title': title,
        'difficulty': difficulty,
        'category': category,
        'tags': tags,
        'statement': statement,
        'module_signature': sig,
        'behavior': behavior,
        'constraints': constraints,
        'example': example,
        'hint': hint,
    })

print(json.dumps(problems, indent=2))
